foxglove/mcap

.github/workflows/ci.yml
docs/.prettierrc.yml
docs/specification/README.md
docs/specification/compression/supported-compression-formats.md
docs/specification/notes/explanatory-notes.md
docs/specification/profiles/README.md
package.json

Prettier has a setting to unwrap lines of text in Markdown. Not wrapping allows editors to display text at the user's desired width, and also reduces the number of lines that have diffs with each edit.

Unwrap lines in Markdown

---

docs/specification/README.md

- Specify record length prefix is uint64
- Specify footer is the last record in a file
- Call out when duplicate keys are not allowed in KeyValues
- Change all "decompressed" to "uncompressed"
- Rename channel_stats to channel_message_counts
- Clarify record CRCs do not include opcode/length, and unify wording
- Fix incorrect description for attachment data

Spec edits and clarifications

---

typescript/scripts/validate.ts
typescript/typings/protobufjs.d.ts

`validate` script now supports `protobuf` and `json` encodings (similar to [ws-protocol](https://github.com/foxglove/ws-protocol)).

typescript: add json and protobuf encoding support to validate script

---

cpp/bench/run.cpp
cpp/examples/bag2mcap.cpp
cpp/mcap/include/mcap/mcap.hpp
cpp/mcap/include/mcap/mcap.inl

```
-----------------------------------------------------------------------------------------------------
Benchmark                                                           Time             CPU   Iterations
-----------------------------------------------------------------------------------------------------
BM_McapWriterBufferedWriterUnchunked/10000                     527408 ns       505043 ns         1059
BM_McapWriterBufferedWriterChunked/10000/1                    3149211 ns      3060438 ns          256
BM_McapWriterBufferedWriterChunked/10000/10                   3027427 ns      2984569 ns          267
BM_McapWriterBufferedWriterChunked/10000/100                  1531306 ns      1531300 ns          454
BM_McapWriterBufferedWriterChunked/10000/1000                  854305 ns …
```

[C++] Add noChunking and noIndexing options

---

docs/specification/README.md

Crc fields provide an additional layer of integrity checking on written data. Rather than add crc fields to every record, we provide crc fields in specific records to allow for opt-in crc checking.
If you want to opt-into crc validation for your messages, write messages into chunks (uncompressed chunks are valid chunks).
If you opt into index records, the footer contains a crc for all the written index data.
Attachment records contain a crc because they cannot appear in a chunk.
Fixes #43

spec: remove crc from Channel Info, Message index, and Chunk Index

---

docs/specification/README.md

Remove _count_ from MessageIndex
Fixes: #45
Fixes: #46
Fixes: #35

Add an Array type to use where KeyValues is not appropriate

---

docs/specification/README.md
docs/specification/notes/explanatory-notes.md

Consolidates the chunked and unchunked docs in the specification, and
enables more flexible opt-in support for various record types.
Importantly, chunks can be used without message indexes, and unchunked
writers may omit all indexing if desired.

Consolidate chunked and unchunked record types

---

cpp/bench/run.cpp
cpp/examples/bag2mcap.cpp
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/errors.hpp
cpp/mcap/include/mcap/mcap.hpp
cpp/mcap/include/mcap/mcap.inl

Add lz4 and zstd compression to McapWriter. The compressors work similarly: they hold an accumulating buffer of uncompressed chunk data until it meets or exceeds the target chunk size, then perform a single shot compression. For zstd, this was benchmarked to be 2x faster than incrementally feeding data in with the streaming compression API.

[C++] Add lz4 and zlib compression to McapWriter

---

go/libmcap/benchmark_test.go
go/libmcap/indexed_message_iterator.go
go/libmcap/lexer.go
go/libmcap/lexer_test.go
go/libmcap/mcap.go
go/libmcap/reader.go
go/libmcap/reader_test.go
go/libmcap/unindexed_message_iterator.go
go/libmcap/writer_test.go
go/mcap/cmd/cat.go
go/mcap/cmd/info.go

Changes the lexer to no longer return errors as tokens, and instead
return an error value on calls to next.

Remove channel from golang lexer

---

docs/specification/README.md

Adds a name field to the metadata and metadata index records. This may
be used to separate metadata records logically (map metadata, launch
metadata) and refer to them by name from the index.

Add name to metadata and metadata index

---

docs/specification/README.md

Change _offset_ to refer to the start of the record and add a length field.
This makes the index record consistent with other index records (chunk, metadata), and
allows a user of the index record to go read the specific attachment record in full.

spec: update attachment index

---

docs/specification/README.md

spec: clarify the `Type` column for record definitions

---

docs/specification/README.md

After discussion, we've formed a consensus that `log_time` is a better term for
the semantics of this field. The `log_time` is the time any writer wants to indicate
a message is logged at.
Fixes: #82

spec: rename record_time to log_time

---

go/libmcap/writer.go
go/libmcap/writer_test.go

Expose the chunk, attachment, message indexes as well as statistics as
public fields on the writer. These are useful if you want to maintain an
external index of the files you write. It saves the need to reread them
for the index data after writing, which would require a seek or range
request.

Go: Expose writer indexes as public

---

docs/specification/README.md

After discussion we've determined that a Map type better aligns with the typical use-case of metadata and that duplicate keys are not necessary for practical use.

spec: change metadata to a Map type

---

go/libmcap/writer.go
go/ros/Makefile
go/ros/bag2mcap.go
go/ros/bag2mcap_test.go

Adds a basic benchmark test for the mcap to bag conversion, and reuses a
message buffer across messages when transcoding.

Minor allocation reductions for go bag transcoder

---

go/mcap/cmd/cat.go
go/mcap/cmd/convert.go
go/ros/bag2mcap.go
go/ros/bag2mcap_test.go
go/ros/ros2db3_to_mcap.go
go/ros/ros2db3_to_mcap_test.go

Swaps the argument order for the bag to mcap conversion function so that
the writer is the first argument, which is more conventional in Go. Also
addresses two issues with the CLI tool - the cat command now indicates
where the input file goes in its help output, and the start and end
flags are now start-secs and end-secs.

Swap arg order for bag conversion functions

---

typescript/src/index.ts
typescript/src/v0/BufferBuilder.ts
typescript/src/v0/Mcap0IndexedReader.test.ts
typescript/src/v0/Mcap0RecordBuilder.ts
typescript/src/v0/Mcap0StreamReader.test.ts
typescript/src/v0/Mcap0StreamReader.ts
typescript/src/v0/constants.ts
typescript/src/v0/parse.ts
typescript/src/v0/types.ts

- Remove CRC parsing for Channel Info, Attachment Index, Chunk Index (#55)
- Add record padding to `Mcap0RecordBuilder` (split from #79)
- Add Data End record
- Add `createdAt` to Attachment record
- Add `writeStatistics` and `writeDataEnd` to `Mcap0RecordBuilder`
- Add test & fix attachment CRC validation

TypeScript reader/writer updates

---

README.md
go/README.md
go/mcap/README.md
package.json

We had some Markdown files that weren't in `docs` so they weren't getting linted.

Run prettier on all Markdown in CI

---

go/.golangci.yaml
go/libmcap/mcap.go
go/libmcap/mcap_test.go
go/libmcap/testutils.go
go/libmcap/writer.go

Adds some tests for the integer reading functions, and also corrects a
bug with the bounds check introduced previously: the check was comparing
against the length of buf, rather than the length of buf[:offset],
which rendered it ineffective.

Add tests for integer reading functions

---

docs/specification/README.md

Adds a `metadata_count` to the `Statistics` record, now that we have `Metadata` records. The descriptions for `Statistics` fields have been clarified to talk about record counts and channel id counts without bringing up the "topics" concept here.
Fixes #98

Add metadata_count to Statistics, clarify Statistics field descriptions

---

go/libmcap/indexed_message_iterator.go
go/libmcap/writer.go
go/libmcap/writer_test.go

Prior to this commit, chunk length in the chunk indexes was getting set
to zero.

go: Ensure chunk length is written to chunk indexes

---

docs/specification/README.md

- Schema `name` appears earlier in the record, for aesthetic purposes.
- A few other strings in the spec are updated (non-breaking).

Move name earlier in Schema record

---

docs/specification/README.md

Add 8 bytes to the Chunk record: a length prefix on the `records` bytes.
Schema, Message, Chunk, and Attachment records all have a `Bytes` field. Of these, Schema and Attachment had a length prefix on their bytes while Message and Chunk did not.
A length prefix allows the record to be extended safely in future spec versions. We do not want to pay the extra cost for adding a length prefix to Message since the record will be so frequent, but since there will normally be far fewer chunks than messages, there doesn't seem to be a strong reason to prevent the Chunk record from being extensible in the future.

Add length prefix to Chunk `records` field

---

tests/conformance/scripts/generate-inputs.ts
typescript/src/v0/Mcap0IndexedReader.test.ts
typescript/src/v0/Mcap0RecordBuilder.test.ts
typescript/src/v0/Mcap0RecordBuilder.ts
typescript/src/v0/Mcap0StreamReader.test.ts
typescript/src/v0/parse.ts
typescript/src/v0/types.ts

Metadata and ChannelInfo records now use `Map<K, V>` instead of `[K, V][]` to match latest spec
Split/adapted from https://github.com/foxglove/mcap/pull/117.

typescript: update metadata and channel info to use Maps

---

typescript/src/v0/types.ts

Seems to have been added accidentally in https://github.com/foxglove/mcap/pull/112.

typescript: remove stray import from inspector

---

docs/specification/README.md
docs/specification/notes/explanatory-notes.md
docs/specification/profiles/ros1.md
docs/specification/profiles/ros2.md

Proposal: Rename `Channel Info` to `Channel`.
Rationale:
- Most records are "info" - it's not clear why we treat `Channel` differently than, say, `Schema`.
- This change also makes "primary key" fields such as `Channel.id` more consistent with their "foreign key" relationship fields such as `Message.channel_id`.
Non-binary breaking, although this change would require updates in client libraries.

Spec: Rename Channel Info record to Channel

---

docs/specification/README.md

Previously this duplicated the "metadata" description.

Spec: Update summary wording for metadata index

---

python/tests/run_writer_test.py
tests/conformance/package.json
tests/conformance/scripts/run-tests/index.ts
tests/conformance/scripts/run-tests/runners/CppStreamedTestRunner.ts
tests/conformance/scripts/run-tests/runners/ITestRunner.ts
tests/conformance/scripts/run-tests/runners/PythonStreamedReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/PythonStreamedWriterTestRunner.ts
tests/conformance/scripts/run-tests/runners/TypescriptIndexedTestRunner.ts
tests/conformance/scripts/run-tests/runners/TypescriptStreamedReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/TypescriptStreamedWriterTestRunner.ts
tests/conformance/scripts/run-tests/runners/index.ts
yarn.lock

This adds basic support for writer conformance tests.
For now this just adapts the harness to support reader & writer tests and adds passthrough writer tests for python & typescript. Implementation of the tests will follow in subsequent PRs.
Writer tests should output the mcap they generate as hex encoded strings of the entire file.

Add writer conformance test support.

---

docs/specification/README.md

~If #126 merges,~ it's impossible to have more than 2^16-1 schemas because Schema.id is a uint16 and id 0 is not allowed.

Change schema_count to uint16

---

tests/conformance/scripts/run-tests/index.ts
tests/conformance/scripts/run-tests/runners/CppStreamedTestRunner.ts
tests/conformance/scripts/run-tests/runners/GoStreamedTestRunner.ts
tests/conformance/scripts/run-tests/runners/ITestRunner.ts
tests/conformance/scripts/run-tests/runners/PythonStreamedReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/PythonStreamedWriterTestRunner.ts
tests/conformance/scripts/run-tests/runners/TestRunner.ts
tests/conformance/scripts/run-tests/runners/TypescriptIndexedTestRunner.ts
tests/conformance/scripts/run-tests/runners/TypescriptStreamedReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/TypescriptStreamedWriterTestRunner.ts
tests/conformance/scripts/run-tests/runners/index.ts

This splits the `ITestRunner` interface into two separate reader & writer interfaces.
This allows us to return binary from writer tests which is more natural for comparison.

Separate test reader & writer interfaces.

---

go/libmcap/mcap.go
go/libmcap/parse.go
go/libmcap/writer.go
go/ros/bag2mcap.go
go/ros/bag2mcap_test.go

Makes a few changes to speed up bag conversion, primarily by reducing
allocations. Includes:
* Switch to an insertion sort for message indexes within chunks, under
presumption they are mostly ordered.
* Reuse allocated message index structures across chunks

Go: bag conversion speed improvements

---

docs/specification/README.md

Add clarifying wording to a few length fields.

Clarify lengths include opcode+length prefix

---

cpp/README.md
cpp/bench/run.cpp
cpp/examples/bag2mcap.cpp
go/libmcap/writer_test.go
go/ros/bag2mcap.go

Fixes a byte slice reuse in bag2mcap
Updates Go & C++ to use `ros1msg` for schema encoding as per https://github.com/foxglove/mcap/blob/main/docs/specification/well-known-schema-formats.md

Fix byte slice reuse; update bag schema encoding to ros1msg

---

go/libmcap/crc_writer.go
go/libmcap/lexer.go
go/libmcap/mcap.go
go/libmcap/parse.go
go/libmcap/resettable_write_closer.go
go/libmcap/utils.go
go/libmcap/write_sizer.go
go/libmcap/writer.go

Improves docstrings for the go public functions in some areas. Also
reorganizes the order of types in mcap.go to match the order in the
spec, removes some unused types, and splits the custom reader/writer
types into their own files.

Go: miscellaneous documentation improvements

---

go/.gitignore
go/mcap/Makefile

None
Don't build static binaries on macOS (not possible). Debatable whether we need this on linux, but it's nice if we plan to generate binaries that people want to run under busybox/alpine.
Closes #89
Closes #183

Go: Only build static binary on linux

---

go/cli/mcap/cmd/convert.go

Previously the code was expecting this environment variable to be set to
a file path, however it is actually a colon-delimited list of filepaths.

Split AMENT_PREFIX_PATH for ros2 bags on conversion

---

go/ros/ros2db3_to_mcap.go

To match https://github.com/foxglove/mcap/blob/main/docs/specification/well-known-schema-encodings.md#ros2msg

ros2db3_to_mcap: change encoding to `ros2msg`

---

go/mcap/writer.go
go/mcap/writer_test.go

Prior to this commit, when a chunk received enough messages to warrant
closing, the timestamps of the final message to the chunk were recorded
to the _next_ chunk, rather than the one to be closed.

Set chunk index start ends before closing chunks

---

go/mcap/writer.go

Removes a comment proposing to reuse message index structures across
chunks, which has already been done.

Remove outdated comment

---

go/mcap/writer.go
go/mcap/writer_test.go

Adds an Offset() method to the writer's public interface, to allow the
caller to retrieve the size of the written file. This was already
tracked internally and is useful for streaming writers that may wish to
record statistics in a database, similar to the public accumulated index
structures.

Go: Expose writer offset

---

go/ros/ros2db3_to_mcap.go

Prior to this commit, if the ros2 conversion function failed to find a
package it was looking for, it would break out of a loop immediately and
error on a check that all requested packages were found. This did not
properly account for the possibility of the package existing in a later
path element. The new code continues instead of breaking so that the
schema may be found in another location if available.

Go: Address ros2 db3 conversion bug for multiple input paths

---

go/mcap/lexer.go
go/mcap/lexer_test.go
go/mcap/mcap.go

Prior to this commit, we were allocating a new buffer for decompressed
chunk data for every chunk, when CRC validation was enabled.

Go: reuse buffer for chunks when validating CRCs

---

docs/specification/README.md

Add clarifying wording to the spec to indicate that if there are no summary records, the `summary_crc` is the crc of the first 1+8+8+8 bytes of the footer (which will necessarily be 02 1400000000000000 0000000000000000 0000000000000000).

Clarify summary_crc begins at Footer record if there are no summary records

---

go/mcap/counting_writer.go
go/mcap/mcap.go
go/mcap/parse.go
go/mcap/writer_test.go

Adds a benchmark tests with three scenarios for writes - lots of messages with large chunks, lots of messages with small chunks, and lots of messages with lots of channels. Adds a couple trivial performance improvements as well: switch away from pointers for the message index entry structures, and reset the chunk crc instead of replacing it.

Add some benchmarks for writer memory consumption

---

cpp/README.md
cpp/bench/run.cpp
cpp/build.sh
cpp/mcap/include/mcap/errors.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl

Fixes various compiler warnings, issues encountered when linking against system libraries, and adds the McapWriter::open(filename, opts) API using the new buffered wrapper around fwrite(), `FileWriter`.

[C++] Fixes for linking against system libraries, McapWriter::open(filename, opts)

---

go/mcap/lexer.go
go/mcap/lexer_test.go
go/mcap/testutils.go

Prior to this commit, when running with chunk CRC validation enabled the
go lexer was not properly accepting zero-valued CRCs as valid, resulting
in errors on files written by writers that opted out of CRC checks.

Go: do not fail on zero'd CRCs

---

.github/workflows/ci.yml
python/setup.cfg

This runs CI jobs on new tags as well as merges. It also bumps the python library version.

Run CI on tags and bump python version again.

---

.github/workflows/ci.yml

Adjust the CI tag rule to run on tags starting with `releases`.

Adjust CI tag rule.

---

typescript/mcap/src/v0/ChunkBuilder.ts
typescript/mcap/src/v0/Mcap0Writer.ts

The TypeScript `Mcap0Writer` now accepts a `chunkSize` option rather than creating a new chunk every 10 messages.
Fixes https://github.com/foxglove/mcap/issues/252

TS writer: add chunkSize param with 1MB default

---

typescript/mcap/src/v0/ChunkBuilder.test.ts
typescript/mcap/src/v0/ChunkBuilder.ts
typescript/mcap/src/v0/Mcap0Writer.test.ts
typescript/mcap/src/v0/Mcap0Writer.ts

Fixed a bug in the TypeScript `Mcap0Writer` where messages with a logTime of 0 could cause chunk index records to be incorrect. Also fixes a bug where channels with a schema id of 0 were rejected by the writer.

TS writer: support messages with logTime 0

---

go/mcap/writer.go
go/mcap/writer_test.go

Prior to this commit, if a chunk contained only messages or only
schemas, an index record would still be written. The record would
incorrectly reflect a start time of 0, which resulted in tooling
interpreting the file as starting at zero instead of the time of the
first message contained within.

Go: do not write chunk indexes for chunks without messages

---

typescript/mcap/src/index.ts
typescript/mcap/src/v0/ChunkBuilder.ts
typescript/mcap/src/v0/Mcap0Writer.test.ts
typescript/mcap/src/v0/Mcap0Writer.ts

Fixed a bug in the TypeScript `Mcap0Writer` where message data would be duplicated between chunks, resulting in quadratic growth.

TS writer: fix duplicate data when using multiple chunks

---

go/cli/mcap/README.md
go/cli/mcap/cmd/attachments.go
go/cli/mcap/cmd/chunks.go
go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/list.go
go/mcap/mcap.go
go/mcap/reader.go

Adds support for listing chunks and attachments in a local or remote
mcap file.

Support a `list` subcommand for listing various records

---

typescript/mcap/src/v0/Mcap0StreamReader.test.ts
typescript/mcap/src/v0/Mcap0Writer.test.ts
typescript/mcap/src/v0/Mcap0Writer.ts

The TypeScript `Mcap0Writer` now supports compressing chunks by passing a `compressChunk` function to the constructor.
Closes https://github.com/foxglove/mcap/issues/253

TS writer: add option for pluggable chunk compression

---

go/cli/mcap/cmd/cat.go
go/mcap/indexed_message_iterator.go

Prior to this commit, the indexed reader in go was not closing the zstd
reader after decompressing chunks, resulting in a leak.

Go reader: close zstd chunks

---

cpp/README.md
cpp/bench/run.cpp
cpp/examples/bag2mcap.cpp
cpp/examples/conanfile.py
cpp/examples/mcapdump.cpp
cpp/mcap/include/mcap/errors.hpp
cpp/mcap/include/mcap/internal.hpp
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/types.inl
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/streamed-reader-conformance.cpp
cpp/test/streamed-writer-conformance.cpp
cpp/test/unit-tests.cpp

Previously, the C++ headers could not be included in a project that was not pulling in the mcap dependencies and directly compiling mcap, since the statically linked dependencies were referenced directly in .hpp files. This refactor leaves only STL includes in mcap/*.hpp files, allowing more flexibility for downstream users such as building mcap as a dynamic or static library that is used in other projects. Build times should also be improved in projects where mcap includes occur in more than once place.
This unblocks progress on https://github.com/ros-tooling/rosbag2_storage_mcap/pull/5

[C++] Replace inline methods with MCAP_IMPLEMENTATION macro, allow headers to be included in downstream libraries

---

.github/workflows/ci.yml
python/mcap/mcap0/writer.py
python/setup.cfg
python/tests/run_writer_test.py
python/tests/test_writer.py

This enables zstd compression by default in the python writer.
This enables zstd compression by default in the python writer and also adds some simple tests of writing compressed files.

Enable compression by default in python writer

---

python/setup.cfg

Add a py.typed file to indicate the python mcap module includes type information
This just adds a an empty py.typed file so that other tools recognize the mcap module as typed.

Add py.typed stub file

---

typescript/mcap/src/v0/Mcap0IndexedReader/index.test.ts
typescript/mcap/src/v0/Mcap0IndexedReader/index.ts
typescript/mcap/src/v0/Mcap0StreamReader.test.ts
typescript/mcap/src/v0/Mcap0StreamReader.ts

Error messages from TypeScript readers now include the header `library` when possible, to aid in debugging.
Closes https://github.com/foxglove/mcap/issues/283

TypeScript: include header.library in parse error messages

---

cpp/README.md
cpp/bench/run.cpp
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/crc32.hpp
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/unit-tests.cpp
cspell.config.yaml

Removes `cryptopp` dependency from the C++ library, replacing it with a custom CRC32 implementation. The motivation for this is that compiling cryptopp exposes a bug in intrinsics headers provided with certain GCC versions (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100985).
The multi-byte CRC algorithm was ported directly from https://github.com/foxglove/crc, which was adapted from https://github.com/komrad36/CRC.
Benchmark results from my MBP (M1 Pro):
```
-------------------------------------------------------------------------------------------------------------
Benchmark                                                   Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------- …
```

cpp: remove cryptopp dependency, add crc32 implementation

---

go/cli/mcap/cmd/channels.go
go/cli/mcap/cmd/schemas.go

Adds support for `mcap list schemas` and `mcap list channels`, similar to `mcap list chunks`.

CLI: Add support for listing channels and schemas

---

cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl

Fixed a dangling reference in LinearMessageView (McapReader::readMessages).
Fixes #295

c++: fix dangling reference by copying Message into LinearMessageView

---

go/cli/mcap/cmd/info.go

Example:
```
messages: 1606
duration: 7.780758504s
start: 2017-03-21T19:26:20.103843113-07:00
end: 2017-03-21T19:26:27.884601617-07:00
compression:
zstd: [14/14 chunks] (50.79%)
channels:
(0) /diagnostics              52 msgs (6.68 Hz)    : diagnostic_msgs/DiagnosticArray [ros1msg]
(1) /image_color/compressed  234 msgs (30.07 Hz)   : sensor_msgs/CompressedImage [ros1msg]
(2) /tf                      774 msgs (99.48 Hz)   : tf2_msgs/TFMessage [ros1msg]
(3) /radar/points            156 msgs (20.05 Hz)   : sensor_msgs/PointCloud2 [ros1msg]
(4) /radar/range             156 msgs (20.05 Hz)   : sensor_msgs/Range [ros1msg]
(5) /radar/tracks            156 msgs (20.05 Hz)   : radar_driver/RadarTracks [ros1msg]
(6) /velodyne_points          78 msgs (10.02 Hz)   : sensor_msgs/PointCloud2 [ros1msg] …
```

CLI: Show per-channel frequencies in mcap info

---

.github/workflows/ci.yml
.gitignore
cpp/.gitignore
cpp/examples/mcapdump.cpp
cpp/mcap/include/mcap/errors.hpp
cpp/mcap/include/mcap/internal.hpp
cpp/mcap/include/mcap/intervaltree.hpp
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/CMakeLists.txt
cpp/test/data/001.mcap
cpp/test/streamed-reader-conformance.cpp
cpp/test/unit-tests.cpp
cspell.config.yaml

C++
* TypedRecordReader callbacks now have fileOffset/chunkOffset arguments
* Removed McapReaderOptions
* Changed McapReader.readSummary() to take a method enum and problem callback
* McapWriter.statistics()
* McapReader.open(filename)
* FileReader
* McapReader.chunkIndexes()
A handful of changes (several of them API-breaking) to add full summary parsing to McapReader, including an option to fall back to a full scan of the file to reconstruct summary information.
A follow-up PR will add one or more methods for querying the interval tree to enable fast seeking for summarized files.

[C++] Summary parsing

---

go/cli/mcap/cmd/info.go
go/conformance/test-streamed-write-conformance/main.go
go/mcap/mcap.go
go/mcap/reader.go
go/mcap/writer.go
go/mcap/writer_test.go
go/ros/bag2mcap.go
go/ros/ros2db3_to_mcap.go

Adds library and profile to the info output. Also switches the writer to
deriving the library version from runtime build info. A Library provided
to WriteHeader will be appended to the derived one with a semicolon
separator.

CLI: Add library and profile to "info" output.

---

go/cli/mcap/go.mod
go/cli/mcap/go.sum
go/ros/go.mod
go/ros/go.sum

Prior to this commit the subprojects referenced each other to allow
simultaneous changes, however this breaks the installation of the CLI
tool via go get github.com/...
This commit removes the mechanism that allowed this. Going forward
separate PRs will be required for updates to different libraries. Leaves
the directives in place for the conformance tests, since they are
necessary there.

Remove replace directives from ros library and cli

---

.github/workflows/ci.yml
python/Pipfile
python/Pipfile.lock
python/setup.cfg

This lowers the required python version from 3.8 to 3.7 for wider compatibility.
This just lowers the version requirement to 3.7.

Support python 3.7

---

README.md
cspell.config.yaml
docs/specification/README.md
docs/specification/mcap.ksy

Added a Kaitai Struct definition for MCAP files.
This allows visualizing MCAP files using https://ide.kaitai.io/:
And on the command line using `$ ksv example.mcap mcap.ksy`:

Add KSY definition for MCAP

---

docs/specification/mcap.ksy

None
Adding `instances` for the file footer and summary sections enables navigating the file using the footer:

Update KSY definition to allow navigation via footer and summary

---

.vscode/launch.json
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/unit-tests.cpp

**C++**
- McapReader.readMessages() will only iterate over the relevant portion of the file if readSummary() has been successfully called and a time range is given
- McapReader.byteRange()
- McapReader.channels()
- McapReader.schemas()
- McapWriter.dataSink()
These are the remaining C++ API methods required to finish the rosbag2_storage_mcap implementation

Add McapReader seeking, channels(), schemas(), byteRange(), McapWriter dataSink()

---

cpp/bench/run.cpp
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/errors.hpp
cpp/test/streamed-writer-conformance.cpp

The C++ compiler will produce an error when a `mcap::Status` is unintentionally discarded. Use a `(void)status` cast to intentionally discard a status.
Also update conanfile license to match this repo's license

Make mcap::Status [[nodiscard]]

---

go/cli/mcap/cmd/schemas.go
go/cli/mcap/go.mod

Prior to this commit, listing schemas coerced the schema data to a
string for display. This works fine for ros but fails for protobuf
schemas. With this commit we parse the protobuf schemas and display them
legibly - though not as valid .proto files, which would be ideal.

CLI: support listing schemas for protobuf mcap

---

go/cli/mcap/cmd/info.go

Adds parenthesized decimal seconds for start/end, next to the existing
RFC3339 stamp.

Display decimal seconds in info output

---

go/mcap/indexed_message_iterator.go
go/mcap/reader_test.go

Prior to this commit, indexed playback of mcap files with the go library
would not deterministically resolve ties on timestamp. With this change
such ties are broken by the physical offset of the message in the chunk.

Go: break ties in indexed reading on chunk offset

---

cpp/test/CMakeLists.txt
cpp/test/data/001.mcap
cpp/test/unit-tests.cpp

None
Fixed an incorrect `>=` check in `Buffer`. Updated tests to generate data using Buffer instead of a fixture file, thus exercising the fixed code.
Found when writing test code for https://github.com/conan-io/conan-center-index/pull/9848

Fix range check in unit test Buffer::read

---

.github/workflows/pages.yml

This will allow us to use a glob in a jekyll config file to include files from the whole docs dir at once.

move docs to subfolder in pages build

---

python/Pipfile.lock
python/mcap/mcap0/chunk_builder.py
python/mcap/mcap0/stream_reader.py
python/setup.cfg
python/tests/test_chunk_log_time.py

This fixes an error in the message start and end time calculation for chunks.
The existing logic would overwrite a message start time of zero if any subsequent messages had a later start time. The new logic is to set the chunk start time and end time to the minimum and maximum times of all received messages.
Fixes https://github.com/foxglove/studio/issues/3073

Fix chunk start & end time calculation

---

.github/workflows/pages.yml

Updates `--hosting-base-path` now that we are hosting the site on mcap.dev rather than foxglove.github.io/mcap.

Update hostingBasePath for Swift docs

---

go/cli/mcap/go.mod
go/ros/ros2db3_to_mcap.go
go/ros/ros2db3_to_mcap_test.go

Restricts db3 conversion to message topics only. Topics in rosbag2 db3
files can also correspond to actions, and we need to ensure that these
are correctly handled before we support them.

Go ROS utilities: Skip action topics in db3 conversion

---

go/cli/mcap/cmd/doctor.go

Fixed a misleadingly-worded error message in `mcap doctor`.

Fix wording for incorrect Chunk.message_start_time in doctor tool

---

typescript/examples/bag2mcap/scripts/bag2mcap.ts

Fixed `@foxglove/mcap-example-bag2mcap` to generate protobuf schemas that have correct dependency information.
protobufjs `toDescriptor()` does not generate the desired filenames or dependencies, so they have to be fixed manually.

TS bag2mcap: fix generated proto descriptor dependencies

---

.vscode/settings.json
go/cli/mcap/cmd/doctor.go
swift/mcap/MCAPStreamedReader.swift

Example output:
> Chunk at offset 127399 has message start time 160401406940, but its chunk index has message start time 137401467398
Also some minor drive-by fixes for TS/Swift.

Improve doctor tool to validate ChunkIndex records

---

.github/workflows/ci.yml

This skips the TestPyPi and PyPi CI steps for forks
This skips the PyPI related Python CI steps for forks so that the publishing secrets are not necessary for CI to succeed for forks.

Don't run PyPi CI steps on forks

---

cpp/README.md
cpp/examples/conanfile.py
cpp/examples/mcapdump.cpp
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/internal.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.inl

None
Removed `fmt` dependency to help with https://github.com/ros-tooling/rosbag2_storage_mcap integration

cpp: remove fmt dependency

---

docs/gh-pages/index.html

This removes the only reference to a specific language or toolchain on the mcap.dev landing page.

Remove go-centric install instructions

---

go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/cat_test.go
go/conformance/test-streamed-read-conformance/go.mod
go/conformance/test-streamed-write-conformance/go.mod
go/go.work
go/mcap/writer_test.go

Fix a bug where cat would display data beyond the bound of a message record.

cli: fix cat reading beyond bounds of data

---

go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/convert.go
go/cli/mcap/cmd/info.go

Fixes a bug introduced recently that caused frequencies in `info` output
to be zero due to unintentional shadowing of a global variable used for
the cat command.
Use of global variables is an artifact of cobra's CLI command code
generation. We can get away from that with a bit of refactoring but
haven't done so yet. As a stopgap, this commit also introduces a
convention of prefixing the globals with the name of the related
command.

CLI: Fix zero-valued frequencies

---

README.md
go/cli/mcap/README.md

Adds some notes about installation of the CLI tool from releases and
source. Also adds a note linking the CLI to the main README, and changes
the link for the go library to point at the library instead of the
parent folder.

Document CLI installation

---

docs/gh-pages/index.html

- mcap CLI tool link should go to main docs, not a releases page

Update links for mcap CLI tool for clarity

---

cspell.config.yaml
python/Pipfile
python/Pipfile.lock
python/mcap/mcap0/stream_reader.py
python/mcap/mcap0/writer.py
python/pyproject.toml
python/setup.cfg

Fixed zstd decompression in the Python reader.
Fixes #389
The `zstd` package did not allow us to pass the uncompressed size as a parameter to the decompress function. The `zstandard` package does. This is required when the writer used a streaming compression API.
Tests are not added because the Python writer uses the one-shot zstd compress API, so does not trigger this issue in the reader (which only occurs when the compressed frame does not include a size value, i.e. when a streaming compression API was used).

python: fix zstd decompression

---

docs/gh-pages/index.html

- Remove instructions using go command for installation
- Resolves https://github.com/foxglove/mcap/issues/393

Remove instructions for go command

---

.gitattributes
go/ros/bag2mcap.go
go/ros/bag2mcap_test.go
go/ros/testdata/markers.bag

Prior to this commit, only the md5sum connection data header would be
converted to channel metadata in bag to mcap conversion. With this
change, we convert everything except the message definition and data
type, which are already represented in the schema/channel structures.

CLI: Ensure connection data headers are all converted

---

typescript/core/.yarnrc
typescript/core/package.json

`@mcap/core` JS/TS package is published at v0.1.1.

Bump TS package version

---

typescript/core/src/index.ts
typescript/core/src/v0/ChunkCursor.ts
typescript/core/src/v0/Mcap0IndexedReader.test.ts
typescript/core/src/v0/Mcap0IndexedReader.ts
typescript/core/src/v0/Mcap0Writer.test.ts

A new `reverse` option for the `readMessages` method of Mcap0IndexedReader. The reverse option emits messages in reverse logTime order (i.e. older messages first).
`startTime` and `endTime` arguments are _not_ reversed when using the `reverse` option. Only the order of the messages produced from the iterator.
Providing a reverse iterator allows users to lookup the latest messages on a topic. This is useful when building a file player and wanting to find the latest available message on all requested topics when seeking to arbitrary locations in an indexed file.

Add `reverse` option to Mcap0IndexedReader#readMessages

---

docs/website/favicon144.png
docs/website/favicon32.png
docs/website/index.html
docs/website/style.css

Minor tweaks to docs page
- Change header link wording from "For C++" to "C++ API"
- Fix styling on header links so the container doesn't get taller on hover
- Remove misplaced `<dl>` wrapper elements
- Add favicon
- Tweak card borders

docs tweaks

---

.github/workflows/ci.yml

None
Make a PR to bump homebrew formula when new release tag is made

Use mislav/bump-homebrew-formula-action to bump homebrew formula upon release

---

go/cli/mcap/cmd/cat.go
go/cli/mcap/utils/ros/json_transcoder.go
go/cli/mcap/utils/ros/json_transcoder_test.go

Fixed a crash in `mcap cat --json` when printing string values that had special characters.
Fixes https://github.com/foxglove/mcap/issues/419

cli: fix json transcoding in cat

---

go/ros/ros1msg/ros1msg_parser.go
go/ros/ros1msg/ros1msg_parser_test.go

Previously the parser assumed that any comment after a field name would
come after a space, like this:
```
Type name # the comment
```
However, there is at least one standard msg definition which breaks this
rule, `ns` in ImageMarker:
https://docs.ros.org/en/noetic/api/visualization_msgs/html/msg/ImageMarker.html
```
string ns\t# namespace, used with id to form a unique id
```
This commit uses the field name description in http://wiki.ros.org/msg#Fields to determine which chars contain the field name.
This slightly changes the behaviour of `mcap cat --json`, which attempts to parse and JSON-encode ROS msg definitions.

cli: parse fields with tab after name

---

go/cli/mcap/cmd/convert.go

Windows users can use `--ament-prefix-path` with a native path separator, and not worry about drive letters `C:\` getting in the way.
Currently `convert` assumes it's running on a unix-like where the path list separator is `:`, but on Windows this doesn't work. This PR uses the platform's path separator.

CLI: use platform-dependent path separators

---

go/ros/ros1msg/ros1msg_parser.go
go/ros/ros1msg/ros1msg_parser_test.go

ROS 1 message deserialization can handle fields with short names. This is very common, so `main` between this commit and  51106da1d4939dcab6a425c4a2324f9f86bbad19 should be considered as broken in this regard.
The ROS1 message definition field parsing regex previously required that any field name had two characters, but this is not the case for many common definitions. This bug originated from my copying the field acceptance regex verbatim from https://wiki.ros.org/msg#field-names, which in retrospect was a mistake.

ros1msg: fix field parsing to handle short names

---

go/ros/ros2db3_to_mcap.go
go/ros/ros2db3_to_mcap_test.go
go/ros/testdata/galactic/share/ament_index/resource_index/rosidl_interfaces/package_a
go/ros/testdata/galactic/share/ament_index/resource_index/rosidl_interfaces/package_b
go/ros/testdata/galactic/share/package_a/msg/NoNewline.msg
go/ros/testdata/galactic/share/package_b/msg/NoNewline.msg

Prior to this commit, we would produce a malformed merged schema in db3
to mcap conversion if a component message definition did not terminate
in a newline. With this change we will insert newlines after message
definitions that do not end in them.

CLI: Don't require newline terminated message defs in db3 conversion

---

go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go
go/mcap/writer.go
go/mcap/writer_test.go

* New `mcap filter` subcommand added, which you can use to filter MCAPs by topic and time range.
* Bug fixed in the go MCAP library when writing attachment indexes, which would cause the attachment
content type to be malformed.
This PR adds a new subcommand to the MCAP CLI tool that allows people to quickly filter topics into and out-of an MCAP file.

CLI: mcap filter subcommand

---

go/cli/mcap/cmd/cat.go

`mcap cat --json` can be used on MCAPs with JSON messages.

CLI: cat --json works for JSON messages

---

docs/specification/README.md

- The file format specification no longer recommends `x-` prefixes for custom profiles/schemas/message encodings.
Fixes https://github.com/foxglove/mcap/issues/370

Remove references to x- prefixes

---

cspell.config.yaml
python/docs/index.rst
python/docs/jsonschema_tutorial.rst
python/examples/jsonschema/PointCloud.json
python/examples/jsonschema/pointcloud_csv_to_mcap.py
python/mcap/mcap0/well_known.py

None.
Adds a tutorial for encoding CSV data into a `foxglove.PointCloud` in an MCAP.

Python: add JSONSchema encoding tutorial

---

typescript/core/src/v0/ChunkCursor.ts
typescript/core/src/v0/Mcap0IndexedReader.test.ts

Under certain situations the Mcap0IndexedReader would produce out of log time order messages from `readMessages`. This change fixes this behavior to produce in order messages.
**Problem Description**
To read data in-order the Mcap0IndexedReader uses a heap of ChunkCursors and reads data from the first cursor in the heap (the "min"). The heap is setup to use the `compare` method exposed on each ChunkCursor instance to compare it to other instances to maintain the properties of a heap and bring the "min" cursor to the "front". The logic within the compare function would try to sort ChunkCursors by which one needed reading next but also which one needed loading next (since the message indexes are read lazily for the cursors). This logic produced an anachronism within the heap which resulted …

[typescript] Fix indexed message reading

---

go/cli/mcap/cmd/filter.go

Prior to this commit, the filter subcommand accepted an
output-compression flag but emitted an unchunked mcap file by default.
This change ensures the output file is always chunked, and also adds an
additional command line option for specifying a chunk size, which is
defaulted to 4MB.

CLI: ensure filter output is chunked

---

cpp/mcap/include/mcap/reader.inl
cpp/test/unit-tests.cpp

Fixed `McapReader::readMessages()` so it doesn't produce an invalid reference when reading an empty file.
We do this `if (!impl_->has_value()) impl_ = nullptr` dance after each `LinearMessageView::Iterator::operator++()`, but we forgot to do it at the beginning.

cpp: fix readMessages() for empty file

---

cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/unit-tests.cpp
cspell.config.yaml

Fixed LZ4 reading and writing in the C++ library.
The C++ reader/writer were using the low-level LZ4 block APIs instead of the common higher-level "frame" APIs.

cpp: fix LZ4 reading/writing

---

go/cli/mcap/README.md

Remove some extraneous prompt formatting from copy/pasted examples.

Minor CLI readme cleanup

---

python/mcap-ros1-support/mcap_ros1/writer.py
python/mcap-ros1-support/tests/test_ros_writer.py

Previously a log time or publish time of 0 would be interpreted as a `None`, and the ros1 writer would write `time.time_ns()` instead.

python: mcap_ros1: treat 0 as a valid timestamp

---

.github/workflows/pages.yml

None
This gives us a way to preview changes to `mcap.dev` before merging. Behind the scenes is pretty simple:
* A bucket exists (currently under the James Sandbox project, but can be moved if needed) with a 90 day lifecycle rule
* A service account exists with push access to that bucket only
* A new secret key has been added to this repo to auth with that service account

pages: upload to preview bucket

---

go/cli/mcap/cmd/doctor.go

Updated `mcap doctor` to check the correctness of Statistics message_start_time/message_end_time.
Fixes #501.
Reports new errors on the file from #501:
```
Examining /Users/jacob/Downloads/whattimeisit.mcap
Statistics has message start time 1659409665222474798, but the minimum chunk start time is 0
Statistics has message end time 9900000000, but the maximum chunk end time is 1659409665222474798
```

doctor: check statistics start/end time

---

python/examples/protobuf/reader.py
python/examples/ros1/reader.py
python/mcap-protobuf-support/mcap_protobuf/decoder.py
python/mcap-protobuf-support/tests/test_decoder.py
python/mcap-protobuf-support/tests/test_writer.py
python/mcap-ros1-support/README.md
python/mcap-ros1-support/mcap_ros1/decoder.py
python/mcap-ros1-support/tests/generate.py
python/mcap-ros1-support/tests/test_ros_decoder.py
python/mcap-ros1-support/tests/test_ros_writer.py

Replaces ROS1 and Protobuf support API for decoding messages.
The previous support libraries used the StreamReader to decode messages, which does not take advantage of the index to search for messages by topic or timestamp. This PR replaces those decoding classes with an iterator adapter, which consumes the `McapReader.iter_messages()` iterator. This allows them to take advantage of the index as well.
Fixes https://github.com/foxglove/private-issues/issues/47

python: support packages can use indexed reader

---

cpp/Makefile
python/Makefile

This commit removes the docker image called `mcap_cpp` from the C++
Makefile. This was being built erroneously in the `hdoc-build` target.
We don't have a need for specific names of containers in this process.
Also, the presence of containers with the same name as images caused
confusion and made this bug harder to spot. Therefore, this commit
removes the `--name` arguments from all `docker run` invocations in
the C++ Makefile.

cpp: use correct image for CI, remove --name

---

python/examples/ros2/py_mcap_demo/package.xml

Just a fix so this builds against latest verson of mcap plugin

Package named incorrectly in python example

---

go/cli/mcap/cmd/doctor.go
typescript/examples/validate/scripts/validate.ts

`mcap doctor` now reports files missing their DataEnd or Footer records.
Fixes #535 
Also updates the TypeScript `validate` script to report extra bytes remaining after parsing.
Ideally doctor would also validate trailing magic. I believe today it does not.

doctor: report missing DataEnd/Footer

---

typescript/core/src/v0/parse.ts

TypeScript Mcap0IndexedReader: fixed an incorrect error message when footer magic was invalid.
Discovered while testing #535 
The `startOffset` was being correctly used for comparison, but was ignored when producing the friendly error message.

TS: fix incorrect error message when magic parsing fails

---

cpp/ci.Dockerfile
cpp/dev.Dockerfile

Seems like there was a CI failure (https://github.com/foxglove/mcap/runs/7980820079?check_suite_focus=true) due to a conan version mismatch. Pin the latest version.

pin conan version to fix CI

---

docs/specification/README.md

Most markdown parsers (like the one used in mkdocs, our documentation generator) treat our "generic" syntax as arbitrary HTML tags, which they are not. GFM seems to treat this case specially, but so that `mcap.dev` can look nice, i'm putting backticks around them all.

specification: use literal syntax for generic types

---

go/cli/mcap/cmd/cat.go

None
`mcap cat` no longer attempts to read stdin if a filename has been provided.
```
$ echo "hello, i am not an mcap" | mcap cat a.mcap
... mcap records...
```
Fixes: #373

CLI: cat: do not read from stdin if filename provided

---

docs/support-matrix.md
go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/cat_test.go
go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go
go/mcap/indexed_message_iterator.go
go/mcap/range_index_heap.go
go/mcap/range_index_heap_test.go
go/mcap/reader.go
go/mcap/reader_test.go
go/mcap/readopts/readopts.go
go/ros/ros2db3_to_mcap_test.go

Adds a `reverse` argument to McapReader.Messages(), letting a user read in reverse order.
Indexed MCAP reads will now return messages in log time order, even if there are chunks with overlapping time ranges.
This PR changes the approach to reading messages using the indexed reader. 
The previous implementation had one active chunk, and all messages were read out of it in ascending log time order before moving on to the next chunk. If two chunks are present in an MCAP with overlapping time ranges, this would cause messages to be read out-of-order.
This PR changes to a scheme where there is one heap containing chunk indexes and message index entries that match the search criteria. 
When a chunk index reaches the top of the heap, the corresponding chunk is …

go: read in log time order with overlapping chunks

---

cspell.config.yaml
docs/specification/appendix.md
python/mcap/mcap/mcap0/well_known.py

Adds `ros2idl` as a well-known schema encoding, as well as a more complete description of the concatenations scheme for `.msg` definitions.

specification: add ros2idl to MCAP spec appendix

---

go/cli/mcap/cmd/doctor.go

`mcap doctor` now exits non-zero if an error is found in the MCAP.
Fixes #356

cli: doctor exits nonzero on failure

---

go/cli/mcap/cmd/info.go

Fixed a bug where `mcap info` would crash if a channel had no schema.
Fixes https://github.com/foxglove/mcap/issues/579

cli: info: don't crash when channel has no schema

---

.github/workflows/ci.yml
go/mcap/go.mod
go/mcap/indexed_message_iterator.go
go/mcap/mcap.go
go/mcap/parse_test.go
go/mcap/reader.go
go/mcap/reader_test.go

Gather metadata index information when reading the summary section. Also, bump required go version to 1.18.

Go: Add support for metadata indexes to reader

---

.github/workflows/ci.yml
.github/workflows/pages.yml

This can be `v1` again now that https://github.com/swift-actions/setup-swift/issues/471 has been fixed. The action has also been moved to a different org.

change setup-swift version back to v1

---

typescript/core/src/pre0/parse.ts
typescript/core/src/v0/ChunkCursor.ts
typescript/core/src/v0/Mcap0StreamReader.ts
typescript/core/src/v0/sortedIndexBy.test.ts
typescript/core/src/v0/sortedIndexBy.ts

- TypeScript library `@mcap/core` can be used without manually installing `lodash`
lodash was used in a few places but there was no dependency on it in package.json. This replaces the few uses of lodash generic  methods with more optimized functions tuned for the @mcap/core library. In particular, it avoids heap allocation of new string  objects during binary searches.
Fixes #588

Remove lodash dependency from @mcap/core

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

Bump C++ library version to 0.3.0

cpp: release 0.3.0 for MIT license change

---

swift/mcap/MCAPRandomAccessReader.swift
swift/mcap/MCAPWriter.swift
swift/mcap/RecordReader.swift
swift/mcap/Records.swift
swift/test/MCAPTests.swift

Renamed variable `MCAP0_MAGIC` to `mcapMagic`.
Follows guidance from https://www.swift.org/documentation/api-design-guidelines/ and https://google.github.io/swift/#global-constants.

Swift: rename MCAP0_MAGIC to mcapMagic

---

go/cli/mcap/cmd/attachments.go
go/cli/mcap/cmd/channels.go
go/cli/mcap/cmd/chunks.go
go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/metadata.go
go/cli/mcap/cmd/schemas.go
go/cli/mcap/go.mod
go/cli/mcap/go.sum
go/cli/mcap/utils/utils.go

Adds metadata counts to mcap info output, and adds an mcap list metadata subcommand.

CLI: Add metadata support

---

.github/workflows/pages.yml
mkdocs.yml

CI pages is failing because we're uploading lots of debug build cache data to our GCS preview bucket unneccessarily.

remove debug output from rust docs

---

python/mcap-ros1-support/mcap_ros1/writer.py

- [Python] Add context manager support (`__enter__` and `__exit__` methods) to the ROS1 support library
Fixes https://github.com/foxglove/mcap/issues/546

[Python] Add context manager support to ros1 writer

---

go/cli/mcap/cmd/add.go
go/cli/mcap/cmd/attachment.go
go/cli/mcap/cmd/attachments.go
go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/get.go
go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/metadata.go
go/cli/mcap/cmd/root.go
go/cli/mcap/utils/utils.go
go/cspell.json

Add support for adding metadata/attachments
Adds support for adding and getting metadata and attachments from an
existing mcap file. To add an attachment to a file,
mcap add attachment demo.mcap -f Makefile
To get an attachment out of the file,
mcap get attachment demo.mcap -n Makefile -o attachment.txt
To add metadata to a file,
mcap add metadata demo.mcap -k foo=bar -k bar=baz -n "my metadata"
To get metadata out of the file,
mcap get metadata demo.mcap -n "my metadata"
{
"bar": "baz",
"foo": "bar"
}
Also fixes a bug in the list attachments subcommand. Previously this was
listing chunks.
Fixes: https://github.com/foxglove/mcap/issues/434
Fixes: https://github.com/foxglove/mcap/issues/372

Add support for adding metadata/attachments

---

.github/workflows/ci.yml

None
cc @foxglove/mcap-cli-maintainers on formula bump PRs.
I think this will require @foxglovebot to be added to the @foxglove org for mentions to work.

cli release: cc maintainers

---

go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/channels.go
go/cli/mcap/cmd/chunks.go
go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/schemas.go

- [cli] Consistent formatting for stderr messages
Fixes https://github.com/foxglove/mcap/issues/437

[cli] Replace log.Fatal*() calls with die()

---

go/cli/mcap/cmd/root.go

- [cli] `--version` or `-v` shows the mcap version
Fixes https://github.com/foxglove/mcap/issues/590. Also removed `--toggle` detritus

[cli] Add --version / -v support

---

.github/workflows/ci.yml
cpp/Makefile

- None
This PR volume mounts `$HOME/.conan/data` to `/root/.conan/data` inside Docker containers specifically for the `ci` Makefile commands, and fixes `hashFiles()` usage in GitHub Actions to ingest conanfile.py inputs rather than the output artifact directory (which does not exist when the hash check is done). The end result is caching of conan build artifacts between CI runs, so the majority of CI time is no longer spent recompiling the protobuf library.
**New CI output:**
```
Packages
lz4/1.9.3:63c2a85d57849e261f98f935b93ecac31ba71b84 - Cache
nlohmann_json/3.10.5:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
protobuf/3.21.1:2b471b60d03a9d59f138a492b962f734618de80a - Cache
zlib/1.2.12:63c2a85d57849e261f98f935b93ecac31ba71b84 - Cache …
```

Fix hashFiles() input for C++ CI caching

---

cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.inl

Get rid from static linking of the zstd in mcap cpp by removing #define ZSTD_STATIC_LINKING_ONLY
We need to link zstd dynamically to be able to use zstd_vendor in ROS2

Get rid from static linking of the zstd in mcap cpp

---

go/mcap/version.go

Bumping the version to get the tag right.

go: bump to v0.1.1

---

go/cli/mcap/cmd/info.go

Adds uncompressed/compressed size details to `mcap info` (in the compression section):
```
compression:
zstd: [248/248 chunks] [2610 MB/635 MB (75.66%)] [12.85 MB/sec] 
```
Note that this UX might not be what the ticket was looking for; we could just as easily leave the per-compression-format statistics untouched and add two separate lines for the uncompressed/compressed details.
An alternative output could be:
```
compression:
zstd: [248/248 chunks] (75.66%) 
uncompressed: 2610 MB @ 52.83 MB/sec
compressed: 635 MB @ 12.85 MB/sec (75.66%) 
```
Open for a debate :)
**GitHub issues**
Resolves: https://github.com/foxglove/mcap/issues/439

mcap info to display the file size

---

cspell.config.yaml
docs/styles/extra.css
docs/theme/main.html
mkdocs.yml

- Use bold font for markdown h2/h3 headings
- Load 600 weight instead of 700 from google fonts. 700 feels quite heavy for the IBM Plex fonts we use.
Preview deploy: https://storage.googleapis.com/foxglove-mcap-dev-preview/2f35fb79ae4aba4dd0a0f097a75c5b9dd134c368/index.html
Before | After
--- | ---

docs: use bold font for markdown h2/h3 headings

---

rust/Cargo.toml
rust/src/read.rs

Adds `read::RawMessageStream`, no changes to existing API
We've run into use cases where we don't care about the specifics of each message's Channel, but just want a way to uniquely identify it. Hashing the Channel each time would be sad and slow, and MCAP already gives us a unique ID for the channel. Use that!
Happy to nitpick names, or whether we'd rather return some
```rust
struct RawMessage<'a> {
header: records::MessageHeader,
data: Cow<'a, [u8]>
}
```
instead of a tuple, etc.
```

rust: Provide RawMessageStream of (header, data) tuples

---

rust/Cargo.toml
rust/examples/conformance_reader.rs
rust/src/records.rs

Removes `serde` dependency for Rust crate
We don't want to force Serde on users just for the sake of the conformance tests. (In what context would you want to serialize individual records of a MCAP to something else?)
Stamp out and stringify them ourselves.
fixes #656

rust: Don't force serde on users for our tests

---

rust/Cargo.toml

Bump version preparing for a release including 136a41777ac064caf0ca6072411c1d8d90f9d73d .

rust: bump version to 0.5.0

---

rust/Cargo.toml
rust/README.md
rust/src/lib.rs
rust/src/read.rs
rust/src/write.rs
rust/tests/common.rs
rust/tests/compression.rs
rust/tests/flush.rs
rust/tests/round_trip.rs
testdata/mcap/demo-uncompressed.mcap

Makes zstd an optional dependency for the Rust library.
This makes it possible to build the Rust library without built-in zstd compression support. The default build will still include it.
Note this also required adding an uncompressed version of the demo.mcap test data because when the Rust code is compiled without zstd it is unable to read the existing demo.mcap for test purposes.
Fixes #648

Make zstd optional in Rust library

---

cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl

Adds `McapWriter::closeLastChunk()`, to allow a writer to clear the chunk buffer into the destination file. 
This is useful if a user wants to push all data written so far to the underlying storage medium with `fsync` or similar. They can call `closeLastChunk()` to write out the chunk buffer, then flush and fsync the underlying IWritable instance.

cpp: add closeLastChunk on McapWriter

---

cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl

Removes the "buffer size" parameter from the FileWriter constructor.
From the sweep below, as of right now varying the buffer size in FileWriter makes no difference to throughput.
`fopen` opens the underlying file in buffered mode, meaning the runtime allocates some buffers and does buffering for us.
Opening the file in unbuffered mode and re-sweeping does show a real drop-off at 8192kb on my M1 mac.
This PR just removes the internal buffer and lets the runtime handle buffering for us. I could alternatively open the file in unbuffered mode and change the default to 16384 - let me know what you think.

cpp: remove redundant buffer from FileWriter

---

docs/specification/appendix.md

Fixed a typo in the appendix. All implementations have been using message_encoding `ros1` to match the `ros1` schema encoding and profile.
Closes #679

Fix typo in ros1 profile spec

---

go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go
go/mcap/reader.go
go/mcap/version.go

* Removes the `--profile` argument from `mcap merge`.
* converts `mcap.Reader.readHeader` into a public method `Header()`.  This works on seeking readers always, and non-seeking readers if no other records have been read from the file.
Reads the profile from each input before merging messages, if they're all the same that's the profile for the new MCAP.
Fixes #684

CLI: merge preserves profile from inputs

---

go/cli/mcap/cmd/doctor.go

Adds a warning to `mcap doctor` when we encounter a schema record with no `data` and no `encoding`.
An empty schema is a pretty odd corner case - the data it refers to is not schemaless, but there is no information that can be used to decode it. The only example I can think of for this is where a user has some JSON messages and there is no `jsonschema` to describe them, but still wants to provide some label to help the decoder figure out what to do with it.
In every other case, this is something the user ought to know about.
fixes #698

CLI: doctor: warn on schema with empty data and encoding fields

---

docs/support-matrix.md

The Swift indexed reader is being used in production as of https://github.com/foxglove/studio/pull/4745
We still have this sentence:
> The Python, C++, Go, and TypeScript MCAP libraries are actively developed. This means that Foxglove actively pursues bug fixes and ensures conformance with the MCAP specification.
That also excludes Rust. I'm not sure if this sentence is very valuable or accurate?

Remove note about Swift library being experimental

---

go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/filter.go
go/mcap/lexer.go
go/mcap/lexer_test.go

* Improves error message from `mcap recover`  and `mcap doctor` on truncated MCAP files.
Before:
```
Failed to read token: Unexpected EOF
```
After:
```
Failed to read next token: MCAP truncated in message index (0x7) record content with expected length 51542, data ended after 50343 bytes
```
* Library users inspecting errors by equality will need to update their error handling of the `mcap.Lexer` next method. Previously they would expect an `io.UnexpectedEOF`, but now they get `mcap.ErrTruncatedRecord` when an MCAP is truncated. Note that `mcap.ErrTruncatedRecord` wraps `io.UnexpectedEOF`, so if they use `errors.Is` they don't have to modify their code.
fixes #697

lexer: expose informative error on truncation

---

cpp/.clang-format
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/visibility.hpp
cpp/mcap/include/mcap/writer.hpp

`dllexport`s all interfaces from `reader.hpp`, `writer.hpp`, and `types.hpp` for usage as a shared library on Windows.
Add `visibility.hpp` to provide platform-dependent macros to allow for `dllexport`/`dllimport` and skipping on non-Windows.
Part of #716 
Part of https://github.com/ros-tooling/rosbag2_storage_mcap/issues/67

Windows dllexport

---

.github/workflows/ci.yml
cpp/build.sh

Windows CI specifies the version of the MCAP library in a hardcoded string, which changed recently and is now wrong.
This PR changes windows CI to use the `cpp/build.sh` script where the version string is specified for other build steps.

cpp: fix windows CI

---

go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go

users can now use multiple exclude patterns with `mcap filter` and it will work.
Fixes #724

CLI: filtering with multiple exclude matchers works

---

go/cli/mcap/cmd/attachment.go
go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go
go/cli/mcap/utils/utils.go
go/conformance/test-streamed-read-conformance/main.go
go/conformance/test-streamed-write-conformance/main.go
go/mcap/crc_reader.go
go/mcap/lexer.go
go/mcap/lexer_test.go
go/mcap/mcap.go
go/mcap/parse.go
go/mcap/reader.go
go/mcap/reader_test.go
go/mcap/testutils.go
go/mcap/utils.go
go/mcap/writer.go
go/mcap/writer_test.go

Adds support for streaming reads and writes of attachment data. With this change, ParseAttachment is dropped as a public function and replaced with a private function, parseAttachmentReader.
A new type AttachmentReader is exposed, which exposes the Data portion of an attachment as a reader that can be streamed. The Attachment type is modified to include a new ContentLength field, to allow the writer to write the attachment length before stream processing the body.
A new option, AttachmentCallback, is exposed in the Lexer. Rather than emitting attachments, the Lexer now parses an attachment reader and calls the supplied callback (if supplied), and consumes any unconsumed bytes from the attachment record (whether or not a callback is supplied).
This is a breaking change in the Go SDK, and …

Go: add support for stream handling of attachments

---

.lfsconfig

This is messing with users' ability to clone using a pure SSH-based authentication method. The `.lfsconfig` file was originally introduced to fix a SwiftPM issue, but this can be mitigated by using `GIT_LFS_IGNORE_DOWNLOAD_ERRORS=1` during the build process on the client side.
Fixes #734

remove .lfsconfig

---

.github/workflows/ci.yml
.github/workflows/pages.yml

Two issues with CI as of yesterday:
Swift actions have been failing because of some failure to fetch or verify GPG keys. Here's an example failure:
https://github.com/foxglove/mcap/actions/runs/3560853685/jobs/5981220840
```
/usr/bin/gpg --import /home/runner/work/_temp/35480592-d4e3-464f-8d31-e52c069463d1
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key D441C977412B37AD: public key "Swift Automatic Signing Key #1 <swift-infrastructure@swift.org>" imported
gpg: key 9F[5](https://github.com/foxglove/mcap/actions/runs/3560853685/jobs/5981220840#step:3:6)97F4D21A5[6](https://github.com/foxglove/mcap/actions/runs/3560853685/jobs/5981220840#step:3:7)D5F: public key "Swift 2.2 …
```

Fix python and swift CI

---

go/cli/mcap/cmd/info.go

Instead of only displaying megabytes in info, this PR allows `info` to dynamically determine the byte unit based on the magnitude of the value.
Before:
```
j@192-168-1-108 mcap % mcap info ../../../rosbag2_2022_11_02-17_25_22_0.mcap
library: libmcap 0.2.0
profile: ros2
messages: 1677
duration: 4.276683915s
start: 2022-11-03T11:25:22.944598562+11:00 (1667435122.944598562)
end: 2022-11-03T11:25:27.221282477+11:00 (1667435127.221282477)
compression:
zstd: [565/565 chunks] [00 MB/00 MB (40.96%)] [0.00 MB/sec] 
channels:
(1) /parameter_events    0 msgs (0.00 Hz)     : rcl_interfaces/msg/ParameterEvent [ros2msg]  
(2) /rosout              6 msgs (1.40 Hz)     : rcl_interfaces/msg/Log [ros2msg]             
(3) /qux               418 msgs (97.74 Hz)    : …
```

CLI: display small byte values with human-readable units

---

rust/src/write.rs
rust/tests/chunks.rs
rust/tests/flush.rs

Adds a new writer option, `chunk_size`, which will automatically break up chunks at a target (uncompressed) size.
Fixes #727

rust: writer automatically breaks chunks at size

---

go/cli/mcap/cmd/attachment.go
go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/cat_test.go
go/cli/mcap/cmd/channels.go
go/cli/mcap/cmd/chunks.go
go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/filter_test.go
go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go
go/cli/mcap/cmd/metadata.go
go/cli/mcap/cmd/schemas.go
go/cli/mcap/go.mod
go/cli/mcap/go.sum
go/cli/mcap/utils/utils.go
go/mcap/go.mod
go/mcap/go.sum
go/mcap/lexer.go
go/mcap/reader.go
go/mcap/writer_test.go
go/ros/go.mod
go/ros/go.sum

Adds Close() methods to the Lexer and Reader types. These are required to avoid a goroutine leak when working with zstd-compressed files.
Fixes: https://github.com/foxglove/mcap/issues/748

Go: address goroutine leak when lexing zstd-compressed mcap

---

cpp/Makefile
cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/read_job_queue.hpp
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/types.inl
cpp/test/conanfile.py
cpp/test/unit_tests.cpp

This PR contains a few changes required to get the `rosbag2_storage_mcap` plugin to actually behave correctly with respect to message ordering and selecting messages by time range.
* Messages with the same timestamp are returned in the order of their position in the file. This is neccessary to have a well-defined return order from ReadMessages, since log timestamps are not required to be unique.
* `MessageView` includes a new "messageOffset" field, informing the reader of the returned messages' offset within the file. This allows readers to tell if a message returned from one iterator is the same message as returned from a different iterator.

cpp: read messages in deterministic order, yield message offset in MessageView

---

.github/workflows/ci.yml

This reverts commit c0f67af1b391f75b49947d9e3302bca207b548d0.
https://github.com/pypa/gh-action-pypi-publish/issues/115 that caused this change is now fixed, can revert.

Revert "ci.yml: pin pypa release action v1.5 (#764)"

---

rust/Cargo.toml
rust/src/write.rs

Changes the default chunking behavior of the Rust writer to break chunks at a finite value. The current default behavior is a footgun and can lead to a situation where a user loses all of their MCAP data if they never break chunks.

rust: set default chunk size to a sane value

---

Package.resolved
Package.swift
swift/mcap/MCAPRandomAccessReader.swift

- Don't export CRC and conformance as products visible by others who depend on this package
- only depend on HeapModule from swift-collections to reduce build time

swift: reduce exported API

---

cpp/README.md
cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/intervaltree.hpp
cpp/mcap/include/mcap/read_job_queue.hpp
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py
cpp/test/unit_tests.cpp

* moves `ReadMessageQueue` and associated classes into the `mcap::internal` namespace.
* Adds an explainer for what is covered under the public API.

cpp: make read_job_queue internal

---

docs/specification/README.md

Currently, clicking this .ksy link on https://mcap.dev/specification/index.html downloads the .ksy file. It would be more useful to display it on GitHub where there's syntax highlighting.

use full url to link to .ksy file

---

go/ros/ros2db3_to_mcap.go
go/ros/ros2db3_to_mcap_test.go
go/ros/testdata/galactic_irregular_symlinks/std_msgs/msg/String.msg
go/ros/testdata/irregular_galactic/std_msgs/msg/String.msg

Replaces the logic in `mcap convert` for ROS 2 files that looks for schema definitions. Previously we would look for message definitions using the ament resource index, but this is a fragile mechanism especially for workspaces with message definitions in nested subdirectories. Several users have had trouble using this, and debugging why their install space isn't exactly correct is a slog. Instead, `mcap convert` searches for a path with the form `<packageName>/msg/<MsgName>.msg` anywhere in one of the directories specified with `ament-prefix-path`.

CLI: search optimistically for message definitions

---

go/ros/ros2db3_to_mcap.go
go/ros/ros2db3_to_mcap_test.go
go/ros/testdata/galactic_irregular_symlinks/std_msgs/msg/String.msg
go/ros/testdata/get_schema_workspace/share/ament_index/resource_index/rosidl_interfaces/example_msgs
go/ros/testdata/get_schema_workspace/share/example_msgs/msg/Descriptor.msg
go/ros/testdata/get_schema_workspace/share/example_msgs/other_subdir/CustomSubdirectory.msg
go/ros/testdata/irregular_galactic/std_msgs/msg/String.msg

**public facing changes**
* modifies the `mcap convert` behavior for ROS 2 .db3 files to
properly use the ament index to find message definitions. This brings with it
the ability to find message definitions in package subdirectories other than
`msg/`.

CLI: fix message definition location in subdirectories

---

docs/specification/appendix.md

Fix `--` being displayed as "–" on the website.

Fix code formatting in spec appendix

---

.github/workflows/ci.yml
cpp/ci.Dockerfile
cpp/dev.Dockerfile
go/cli/mcap/go.mod
go/cli/mcap/go.sum

This should fix an installation error that occurs when installing via
go install github.com/foxglove/mcap/go/cli/mcap@latest
When running the install locally the build succeeds; I think usage of go workspaces is overriding the dependency specified in the go.mod file. Need to understand the mechanics of that better to propose a long-term fix to keep these in sync. For now this just updates the deps which I expect will resolve the immediate problem.

Update mcap dependencies in CLI tool

---

go/cli/mcap/cmd/info.go

Prior to this commit, if the duration of an mcap file were less than a second we would divide by zero when computing the frequency on a topic. This was because a float was getting cast to uint64 and getting truncated before being used as the denominator in the frequency computation.

Avoid divide by zero in info on subsecond inputs

---

go/mcap/version.go

Increases the major version of the the `https://github.com/foxglove/mcap/go` library to 1.

go: bump library version to v1.0.0

---

.github/workflows/ci.yml
cpp/ci.Dockerfile
cpp/dev.Dockerfile

No changes to public APIs or code, just CI infrastructure.
It seems to be common practice for Conan recipes to publish new revisions of recipes that require newer version of conan itself, without updating the semantic version of the library. This has periodically required us to update our Conan version installed in CI in order to keep CI working. This PR solves this problem by always installing the latest 1.x.x version of Conan available at test time. There are other possible solutions to this problem:
1. We could pin specific recipe revisions in `mcap/conanfile.py`. This would be fine for CI, but would negatively impact users who install `mcap` through Conan, because they are no longer able to select a recipe revision that works for their …

CI: install latest compatible version of conan

---

docs/specification/README.md

This makes an explicit prohibition on zero opcodes. Zero opcodes were previously not designated as reserved for either future mcap development or application extensions - nothing was said about them. However some special handling is warranted because readers should not ignore them, or else empty file content (interpreted as zero opcodes followed by zero-length messages) may parse without an error.
This changes the behavior from undefined to defined as an error.

Spec: prohibit zero opcodes

---

go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go

Fixes a bug where `mcap filter` (and filter-derived commands like `compress`) would duplicate channel and schema records with every message.
Fixes #815

cli: filter does not duplicate schema records

---

python/mcap-protobuf-support/mcap_protobuf/writer.py
python/mcap-ros1-support/mcap_ros1/writer.py
python/mcap-ros2-support/mcap_ros2/decoder.py
python/mcap-ros2-support/mcap_ros2/writer.py
python/mcap/mcap/writer.py
python/mcap/tests/run_writer_test.py

- [Python] Add Writer class constructor args `enable_crcs=True`, `enable_data_crcs=False`
- [Python] Expose `chunk_size`, `compression`, and `enable_crcs` args to Writer constructors for mcap-ros1-support, 
mcap-ros2-support, and mcap-protobuf-support
- [Python] Fixed mcap-ros2-support to throw McapROS2WriteError when schema parsing fails
Also includes misc typing improvements

[Python] Add enable_crcs and enable_data_crcs Writer options. Expose chunk_size, compression, and enable_crcs to support writers

---

go/cli/mcap/cmd/doctor.go

- [cli] `mcap doctor` now defaults to silent for conforming MCAP files. The previous behavior can be restored with `--verbose`/`-v`
Following http://www.linfo.org/rule_of_silence.html as the default behavior for the `mcap doctor` command. The previous behavior is still available through a new verbose flag.

[cli] `mcap doctor --verbose`, default to silence

---

cpp/examples/conanfile.py
cpp/examples/protobuf/CMakeLists.txt
cpp/examples/protobuf/unit_tests.cpp
cpp/examples/protobuf/write_zfp_images.cpp
cspell.config.yaml

- [C++] Adds an example writing ZFP data to `foxglove.CompressedImage` messages

[C++] Add ZFP image writing example

---

docs/specification/README.md
go/cli/mcap/cmd/doctor.go

* The MCAP specification now recommends against MCAPs from mixing chunked-and un-chunked writing in the same file.
* `mcap doctor` now reports a warning for MCAPs containing Message records in the data section with Chunk Indexes in the summary section.

add note recommending against mixed chunking

---

go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go

* Fixes a crash in `mcap merge` where a schemaless channel (ie. one with schema_id == 0) would cause the CLI tool to crash.
Fixes #829

CLI: fix bug where `mcap merge` crashed on channels with schema_id == 0

---

typescript/core/src/McapStreamReader.test.ts
typescript/core/src/McapStreamReader.ts

- [TypeScript] `McapStreamReader` accepts a `noMagicPrefix` option that allows parsing to start past the beginning of an MCAP file

[TypeScript] Add `noMagicPrefix` option to McapStreamReader to allow parsing to start past MCAP_MAGIC

---

go/mcap/lexer.go

Exports an error type for invalid zero opcodes encountered by the lexer. We skip unrecognized opcodes for forward compatibility, but zero in particular is considered to be an error. It would be useful for calling code to be able to recognize this case and handle it appropriately.

Export error type for invalid zero opcode

---

go/ros/ros1msg/ros1msg_parser.go
go/ros/ros1msg/ros1msg_parser_test.go

Expands the set of ROS1/2 message definitions accepted by `mcap convert`, by allowing fields that have type and name separated by spaces and/or tabs.
the ROS1 msg spec says the type and name of a field are separated by a "space", however in actuality the parser is more lenient:
https://github.com/ros/ros/blob/noetic-devel/core/roslib/src/roslib/msgs.py#L624
what this is doing is breaking a line into parts by space and calling `.strip()` on them, which also removes tab characters. This means the parser accepts fields separated by a combination of whitespace characters (space and tab), so long as there is at least one space in there. This PR mirrors that behavior in the Go parser.

go/ros: rosmsg parser accepts and/or spaces between field name and type

---

go/cli/mcap/README.md

Specify that installing with go install is not supported.

Update dependencies & remove go.work

---

go/cli/mcap/cmd/info.go

`mcap info` on files with a duration > 2**63s will have their duration, start and end times printed correctly.
* fix a bug in decimalTime which would print timestamps > 2^63ns as negative numbers
* fix a bug where very long durations in MCAP would be printed as negative.
For the linked file in #822, returns:
```
$ mcap info
library: libmcap 1.0.0
profile: 
messages: 300
duration: 18446744073.620s
start: 0.000000000
end: 18446744073.619617024
compression:
zstd: [1/1 chunks] [221.93 KiB/3.77 KiB (98.30%)] [0.00 B/sec] 
channels:
(1) image              100 msgs (0.00 Hz)   : foxglove.CompressedImage [protobuf]    
(2) camera_info        100 msgs (0.00 Hz)   : foxglove.CameraCalibration [protobuf]  
(3) image_annotations  100 msgs (0.00 Hz)   : foxglove.ImageAnnotations [protobuf] …
```

CLI: info: handle durations > 2**63

---

cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/writer.hpp

- [C++] Fixes `-Wextra-semi`, `-Wsuggest-override`, `-Wsuggest-destructor-override`, and `-Winconsistent-missing-destructor-override` compiler warnings

[C++] Fix warnings from extra semicolons and missing override keywords

---

python/mcap-ros2-support/README.md

None
The example was outdated as commit 8ee1d0f removed the 'topic' member for the McapROS2Message class. It is now under 'channel.topic'

Update example for mcap_ros2.reader

---

go/mcap/indexed_message_iterator.go

Reads full summary section into memory before parsing, rather than pulling it into memory over multiple calls to Read(). Will use more memory than before (I think memory usage for the associated data will double during the function call) but outside the function call should be same as before.
I think the users who will benefit from this will be,
* Users with huge numbers of chunks
* Users with slow and/or remote disks

Speed up the info subcommand

---

go/mcap/indexed_message_iterator.go

This reverts to previous behavior of determining the end of the summary section in the indexed reader by scanning for the footer. This change was introduced unnecessarily in the eventual implementation of the surrounding feature.

Go indexed reader: locate summary section end by scanning for footer

---

typescript/core/package.json
typescript/core/src/ChunkCursor.ts
typescript/core/src/McapIndexedReader.test.ts

TypeScript @mcap/core: fixed an issue where `readMessages({ reverse: true })` and `readMessages({ reverse: false })` would return messages in the same order when multiple messages were at the same timestamp.
`Array#sort()` is a stable sort. This means if multiple messages have the same timestamp, `sort(([a, b]) => b - a)` and `sort(([a, b]) => a - b)` would keep them in the same order. Instead of changing the comparator, we use `Array#reverse()` in the reverse case.
Note that this fix addresses messages within one chunk. It's possible there is still a similar issue when merging across multiple chunks.
Relates to https://github.com/foxglove/studio/issues/5551 / FG-2498

typescript: make forward and reverse iterators true opposites with multiple message at same timestamp within a chunk

---

cspell.config.yaml
docs/specification/README.md

The metadata `name` of `map_metadata` is redundant, we know it is a metadata record so we don't need that in the name. Also, the `map` part doesn't match any of the example key/values in the next line.

Better example for metadata name

---

go/ros/ros1msg/ros1msg_parser.go
go/ros/ros1msg/ros1msg_parser_test.go

Prior to this commit, if a ROS 1 message definition contained both qualified and unqualified complex types in a particular order, it would incorrectly infer the parent package of a succeeding unqualified type, resulting in an erroneous failure to find a submessage definition. For a concrete example, a message definition like this:
```
Foo foo
===
MSG: Foo
other_package/Bar bar
FooBar foobar
===
MSG: other_package/Bar
string data
===
MSG: original_package/FooBar
string data
```
would result in the parser attempting to look up other_package/FooBar for FooBar's type definition, instead of looking for it in the parent package of the overall type.

Fix bug in ros1msg parser

---

go/cli/mcap/cmd/convert.go

Prior to this commit, conversion of bag to unchunked MCAP was slower than to chunked MCAP, due to the unchunked conversion using unbuffered IO.
Now we use a buffered writer in both cases, and the unchunked conversion is appropriately faster.

Use buffered IO in mcap conversion

---

go/cli/mcap/cmd/cat.go
go/cli/mcap/utils/ros/json_transcoder.go
go/cli/mcap/utils/ros/json_transcoder_test.go

This speeds up the ROS to JSON transcoder by removing dependency on the encoding/json package from both it and the cat command.
Prior to this commit, JSON transcoding spent inordinate amounts of CPU time compacting the JSON the transcoder was emitting, however that JSON was almost compact already. Removing the encoder from the cat command revealed that the encoding of strings out of the transcoder was not compact - they got encoded as a quoted string followed by a newline. Removing encoding/json from the transcoder and replacing it with strconv.QuoteToAscii fixed this.

Speed up ROS to JSON transcoder

---

go/cli/mcap/utils/ros/json_transcoder.go
go/cli/mcap/utils/ros/json_transcoder_test.go

Rather than printing the `go` default representation of NaNs and Infs, the ROS JSON transcoder now follows the lead of `protojson` when representing NaN float values. 
See the [protojson docs under "float, double"](https://protobuf.dev/programming-guides/proto3/#json), and the [source code here](https://github.com/protocolbuffers/protobuf-go/blob/f221882bfb484564f1714ae05f197dea2c76898d/internal/encoding/json/encode.go#L148). I chose this because that's the simplest way to get consistent output between the set of transcoders we support currently (ROS1 and protobuf).

CLI: represent NaNs consistently in cat --json

---

go/cli/mcap/cmd/root.go

This adds a --profile switch to all commands. When supplied, it will generate pprof CPU and memory profiles of command execution and write them to files.

Add profile switch for CLI operations

---

go/cli/mcap/cmd/doctor.go

`mcap doctor` no longer reports an error for channel records with schema ID 0. This is not an error for message encodings that do not require a schema to decode.

doctor: do not error on schemaless channels

---

typescript/examples/text-annotation-demo/.eslintrc.js
typescript/examples/text-annotation-demo/package.json
typescript/examples/text-annotation-demo/scripts/Scene.ts
typescript/examples/text-annotation-demo/scripts/main.ts
typescript/examples/text-annotation-demo/tsconfig.cjs.json
typescript/examples/text-annotation-demo/tsconfig.json
yarn.lock

Add Typescript example that creates text annotations on an image. 
This also upgrades `@foxglove/schemas` to 1.3.0

TypeScript Text Annotations example

---

python/mcap-protobuf-support/mcap_protobuf/reader.py

None
Fix docstring parameter name for McapProtobufMessage.

Fix McapProtobufMessage docstring

---

.gitattributes
go/ros/bag2mcap.go
go/ros/bag2mcap_test.go
go/ros/testdata/markers.bz2.bag

Prior to this commit, the bzip2 decompression was broken on bags with more than one chunk. The chunk reader was getting set to a basic reader on the underlying chunk data, rather than a bz2 decompressor (on chunks after the first).
This fixes that and also does a minor refactor to remove the concept of a resettable reader. This was only applicable to the lz4 decompressor previously (out of three - lz4, none, and bz2) and existed to fake generic support for resetting readers when underlying readers didn't support that. Rather than doing that, special case lz4 and use the other two reader types directly.

Fix mcap conversion for bzip2 bags

---

cpp/mcap/include/mcap/reader.inl
cpp/test/unit_tests.cpp

Header records will now be parsed correctly, instead of duplicating the profile into both profile and library fields.
Fixes https://github.com/foxglove/mcap/issues/887

cpp: fix header parsing

---

go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/doctor_test.go
go/mcap/writer.go

* Doctor will no longer raise an error if a chunk is present with no messages.
* Doctor will no longer raise an error when a schemaless channel record is present in a chunk. This was previously updated to not report an error, but that change only applied to channels outside of chunks.
* `mcap.Writer` now correctly sets the chunkEndTime to 0 for chunks with no messages, as specified in the spec: https://mcap.dev/specification/index.html#chunk-op0x06 .

CLI: remove MCAP doctor on chunks with no messages, schemaless channels

---

.github/workflows/ci.yml

N/A
Go version used by GitHub Actions is read from `go.work` file, so there is a single source of truth for minimum required Go version.

Auto detect Go version in GitHub Actions

---

cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl

So that I can browse metadata from indices in C++ client

CPP: add getter for metadata indices

---

go/cli/mcap/cmd/attachment.go
go/cli/mcap/utils/utils.go
go/cli/mcap/utils/utils_test.go

Previously this used the filename and couldn't be specified.

CLI: Add capability to specify attachment name

---

website/src/pages/index.tsx

- Update copy on MCAP home page 
- All features should be nouns (e.g. "Self-contained files" vs. "Self-contained")
- All descriptions should start with verbs (e.g. "Stores ..." vs. "MCAP is the ideal format for storing...")

Update copy on MCAP home page

---

go/cli/mcap/cmd/attachment.go
go/cli/mcap/cmd/metadata.go
go/cli/mcap/testutils/buf_read_write_seeker.go
go/cli/mcap/testutils/buf_read_write_seeker_test.go
go/cli/mcap/utils/checksumming_write_counter.go
go/cli/mcap/utils/checksumming_write_counter_test.go
go/cli/mcap/utils/mcap_amendment.go
go/cli/mcap/utils/mcap_amendment_test.go
go/cli/mcap/utils/utils.go
go/mcap/indexed_message_iterator.go
go/mcap/mcap.go
go/mcap/reader.go
go/mcap/writer.go

Changes the implementation of "mcap add attachment" and "mcap add metadata" to append to the data section in place, then overwrite an updated summary section with all offsets and CRCs updated.
This makes adding attachments and metadata very fast, and constant time with respect to size of the file. Prior to this commit, each one did an overwrite.

Support fast summary section rewrites

---

website/src/icons/index.ts
website/src/pages/index.module.css
website/src/pages/index.tsx

- Add header to logos section; link each logo to website

Add header to logos section; link each logo to website

---

python/mcap-protobuf-support/setup.cfg

Tighten python protobuf dependency to `<=4.21.11` to fix potential segfault
Reading an mcap file with `mcap-protobuf-support` can lead to a segfault which is very likely related to https://github.com/protocolbuffers/protobuf/issues/12047 (see https://github.com/protocolbuffers/protobuf/issues/12047#issuecomment-1622405787 for reproduction steps). This patch tightens the python protobuf dependency to `<=4.21.11` as the segfault apprently only happens from `4.21.11` onwards.
Fixes FG-3792

Tighten python protobuf dependency to `<=4.21.11` to fix potential segfault

---

go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go

CLI commands `filter`, `compress`, `decompress`, and `recover` no longer fail on schemaless channels (schema id = 0).
Don't fail when encountering schema ID 0.
Fixes FG-4182
See also:
- https://github.com/foxglove/mcap/issues/829
- https://github.com/foxglove/mcap/issues/847
- https://github.com/foxglove/mcap/issues/579

mcap filter: don't die on schema id 0

---

cpp/bench/conanfile.py
cpp/bench/run.cpp
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/conanfile.py
cpp/test/unit_tests.cpp

Writing MCAPs with many channels is faster by anywhere between 1% and 20%, depending on conditions.
comparison on my M1 Mac ([see instruction for interpreting output here](https://github.com/google/benchmark/blob/main/docs/tools.md))
```
Benchmark                                                                         Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_McapWriterFileWriterChunkedManyChannels/786432/1                            -0.0366         -0.0366        999498        962936        999439        962867
BM_McapWriterFileWriterChunkedManyChannels/786432/1 …
```

cpp: re-use allocations for message indexes in writer

---

python/mcap/mcap/reader.py
python/mcap/tests/test_reader.py

When attempting to "proxy" a generator function in python, using `return gen()` is wrong. `return val` constructs a StopIteration exception with `val` and raise it, not doing what you want.
This PR fix this by using `yield from`, also adds a test to secure the no summary mcap processing logic.

fix python reader support for mcap without summary

---

cpp/mcap/include/mcap/writer.hpp

Fix an outdated link to documentation in writer.hpp

Fix outdated link in C++ header

---

.github/workflows/ci.yml

None
Fix npm publish step for typescript @mcap/core package.

Fix typescript npm publish CI steps

---

Package.swift
cspell.config.yaml
swift/crc/CRC32.swift

Fixed built of MCAP Swift library on iOS
The ARM intrinsics don't seem to work on iOS. Maybe there is some magical compiler flag to enable them, but I couldn't find it.

swift: don't try to use ARM intrinsics on iOS

---

python/examples/ros1/reader.py

Fix python ROS1 example
Fixes python ROS1 example. Matches the [ros2 reader example](https://github.com/foxglove/mcap/blob/2a1f9c62b30ca88725a2cd6b6227e36c632ab4ab/python/examples/ros2-noenv/reader.py#L8-L12) now
Fixes FG-4717

Fix python ROS1 example

---

go/cli/mcap/go.mod
go/cli/mcap/go.sum
go/mcap/indexed_message_iterator.go

Prior to this commit, when reading a chunk into memory we would read it (internally, in io.ReadAll) into a resizing buffer and need to resize it several times up to final size. Since we know the final size in advance we can preallocate and save those allocations/copies.

Go: Allocate less in indexed message chunk loading

---

go/mcap/version.go

This skips v1.0.2 - that tag was pushed but this file wasn't updated, so the tag is wrong.

Bump go library version

---

go/cli/mcap/cmd/attachment.go

Previously this parameter did not function. Not sure if it never functioned or if we lost the support at some point.

CLI: Properly support --name parameter on add attachment

---

.github/workflows/ci.yml

None
Update Homebrew formula path which changed in https://github.com/Homebrew/homebrew-core/pull/139592.
Relates to FG-4760

Update Homebrew formula path

---

cpp/examples/bag2mcap.cpp
cpp/examples/jsonschema/writer.cpp
cpp/examples/protobuf/CMakeLists.txt
cpp/examples/protobuf/dynamic_reader.cpp
cpp/examples/protobuf/static_reader.cpp
cpp/examples/protobuf/writer.cpp

None
- remove unused include
- use explicit type conversion
- ignore C4267 and C4244 for 3rd_party protobuf generate codes
- prefer constexpr

cpp: fix warning in examples on msvc

---

go/cli/mcap/cmd/info.go
go/cli/mcap/utils/utils.go

This aligns the spacing in the upper part of the "mcap info" output.

Tidy upper part of info table

---

.github/workflows/ci.yml
cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py
cpp/test/unit_tests.cpp

Multiple iterators created from LinearMessageView::begin() will compare to `true`.

fix: LinearMessageView begin does not compare equal to begin

---

.github/workflows/website.yml

None
This PR failed to run `docs-deploy` because it was authored by dependabot: https://github.com/foxglove/mcap/pull/977
This copies similar logic that we use in `ci.yml` to exclude this job for dependabot. It's okay to skip because this job is not marked as a required check.

Don't run docs-deploy job on Dependabot PRs

---

cpp/README.md

None
Fixed a spelling error in the CPP API readme.

Fix spelling in Readme

---

go/Makefile
go/cli/mcap/cmd/attachment.go
go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/cat_test.go
go/cli/mcap/cmd/channels.go
go/cli/mcap/cmd/chunks.go
go/cli/mcap/cmd/convert.go
go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/doctor_test.go
go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go
go/cli/mcap/cmd/get.go
go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/list.go
go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/metadata.go
go/cli/mcap/cmd/root.go
go/cli/mcap/cmd/schemas.go
go/cli/mcap/cmd/version.go
go/cli/mcap/testutils/buf_read_write_seeker.go
go/cli/mcap/utils/mcap_amendment.go
go/cli/mcap/utils/ros/json_transcoder.go
go/cli/mcap/utils/utils.go

Lint mcap cli

---

cpp/examples/protobuf/writer.cpp

None
Example code generates negative nanosecond values in the timestamp.
Before:
After:

fix negative timestamp in cpp protobuf example

---

rust/Cargo.toml
rust/src/records.rs

Updates the rust library to use binrw v0.12.0.
Updates the rust library to use binrw v0.12.0, which is compatible with the latest nightly compiler. This is unfortunately necessary because docs.rs builds docs using a nightly compiler that we don't control, and without it our docs don't build.

rust: update binrw to v0.12.0

---

rust/src/read.rs

There should be no changes in public API caused by this change.
`read_record_from_slice` was checking that buffer size is bigger than 5 but was trying to read a `u8` and `u64` which are in total 9 bytes. This was causing panics when reading malformed mcap files or otherwise malformed streams.
I added some simple tests as well but they aren't very robust (I don't check parsing of records).

[Rust - bugfix] read_record_from_slice checking wrong size of buffer wrong

---

.github/workflows/ci.yml
.github/workflows/website.yml
python/Pipfile
python/Pipfile.lock
python/mcap-protobuf-support/mcap_protobuf/reader.py

Use Python 3.8 for CI builds 
Ensures that Python3.8 is used for CI. This was not the case so far as `pipenv` was "resetting" the python version:
```
make lint
shell: /usr/bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/3.7.17/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.7.17/x64/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.17/x64
Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.17/x64
Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.17/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.17/x64/lib
SETUPTOOLS_ENABLE_FEATURES="legacy-editable" pipenv install --dev --deploy
Creating a virtualenv for this project...
Pipfile: /home/runner/work/mcap/mcap/python/Pipfile
Using /usr/bin/python3 (3.10.12) to create virtualenv...
created virtual …
```

Use Python 3.8 for CI builds

---

python/mcap-ros2-support/mcap_ros2/_dynamic.py

None
Fixes issue on Windows, where empty lines in the ROS2 message definitions would be replaced by `\r\n`.
The regex-patterns don't handle this, which led to an `InvalidFieldDefinition` exception later on in `parse_message_string()`.
See relevant documentation on `os.linesep` here: https://docs.python.org/3/library/os.html#os.linesep

Python: Fix ROS2 message definition parsing on Windows

---

go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/cat_test.go
go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/info_test.go

`mcap cat` used to crash on some valid, but uncommon files. This fixes the crash.
Mcap spec [allows for a missing schema](https://mcap.dev/spec#channel-op0x04).
Currently, `mcap cat` crashes with a nil pointer dereference on such a file (unless you pass `--json`).
After this change, `mcap cat` will print `[no schema]` instead of a schema for schemaless channels.
Also added another test to `cat_test.go`, and added tests for `mcap info` in `info_test.go`

Fix `mcap cat` SIGSEGV when no schema present

---

go/cli/mcap/cmd/info.go

For `mcap info`, removes channel hz display if there are no or one messages in a channel. This avoids displaying an ugly `NaN` or `Inf`.
Before:
```
j@192-168-1-108 python % mcap info ~/this.mcap                                
library:   python mcap 1.1.1                                        
profile:                                                            
messages:  1                                                        
duration:  0s                                                       
start:     2023-11-02T05:34:10.165983+11:00 (1698863650.165983000)  
end:       2023-11-02T05:34:10.165983+11:00 (1698863650.165983000)  
compression:
zstd: [1/1 chunks] [234.00 B/153.00 B (34.62%)] 
channels:
(1) sample_topic  0 msgs (NaN Hz)    : sample [jsonschema]  
(2) sample_topic  1 msgs …
```

do not render hz if no messages

---

go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go
go/conformance/test-read-conformance/main.go
go/mcap/indexed_message_iterator.go
go/mcap/range_index_heap.go
go/mcap/range_index_heap_test.go
go/mcap/reader.go
go/mcap/reader_options.go
go/mcap/reader_test.go
go/mcap/unindexed_message_iterator.go
go/ros/ros2db3_to_mcap_test.go

Includes metadata records from input files in mcap merge via a new read option. This required a breaking change to read options to avoid a dependency cycle: since I need to supply a callback option to apply to metadata records, the readopts package required awareness of "mcap" while "mcap" required awareness of readopts for configuration.
To address this I have moved readopts.go under the mcap package. Users who upgrade the library will need to swap out the package name if they are using any options.

Include metadata in mcap merge

---

go/cli/mcap/cmd/convert.go
go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go

go/cli: Coalesce identical channels by default
Changes the default behavior of `mcap merge` to automatically coalesce identical channels. Channels are considered identical when their topic, schema, message encoding and metadata equals. One can force coalescing of channels with different metadata with `--coalesce-channels force`. Channel coalescing can also be completely disabled with `--coalesce-channels none`.

go/cli: Coalesce identical channels by default

---

go/cli/mcap/cmd/sort.go
go/cli/mcap/cmd/sort_test.go
go/mcap/reader.go
go/mcap/reader_test.go
go/mcap/version.go

Adds a "sort" subcommand to the mcap CLI tool. This will rewrite the messages into a new file, physically sorted on time.

Add subcommand for sorting a file

---

go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go

Fixes bug where the MCAP cli would segfault when using `filter -y` or `filter -n`.
Previously the `compileMatchers` function would build an array of matchers by appending to it, but the array was already initialized with a non-zero length, resulting in the first N entries of that array being uninitialized matchers. This caused a segfault when it came time to use those matchers.

cli: fix segfault bug when using filter args

---

cpp/Makefile
cpp/README.md
cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/errors.hpp
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/CMakeLists.txt
cpp/test/conanfile.py
cpp/test/unit_tests.cpp

Adds two new build-time flags to optionally disable `zstd` and `lz4` support. These are `MCAP_COMPRESSION_NO_ZSTD` and `MCAP_COMPRESSION_NO_LZ4`.
When reading MCAP files, if the reader encounters a known compression method but is compiled without support for it, it will yield `Status::UnsupportedCompression`.
Based on https://github.com/foxglove/mcap/pull/1008
A new test binary is added to CI, which exercises these build-time flags.

cpp: add build-time flags to make compression dependencies optional

---

python/mcap-protobuf-support/setup.cfg

Relax version restrictions of protobuf dependency
Changed the protobuf version restrictions to exclude the 4.22-4.24 which could lead to segmentation faults when reading a mcap file. We previously tightened it in https://github.com/foxglove/mcap/pull/919

Relax version restrictions of protobuf dependency

---

go/cli/mcap/cmd/metadata.go

Prior to this commit, the printed metadata was wrapped/formatted incorrectly when running `mcap list metadata`. This commit fixes it by removing the pretty json format – making the metadata column print only 1 line.

Fix metadata rendering issue

---

.github/workflows/ci.yml
.github/workflows/website.yml

move corepack enable before actions/setup-node

---

typescript/support/package.json

None
Follow-up from #868 – realized 1.0.1 is a weird first version number.

Set @mcap/support to 1.0.0 before first publish

---

typescript/browser/package.json
typescript/core/package.json
typescript/nodejs/package.json
typescript/support/package.json

None
Some changes to typedoc changed/renamed how the "entryPoint" setting works, which was breaking the TS docs at https://mcap.dev/docs/typescript/.
Before:
After:

Fix typedoc configs

---

.github/workflows/ci.yml

None.
I previously configured OIDC in pypi and test.pypi for all of our MCAP packages, see for example https://pypi.org/manage/project/mcap-protobuf-support/settings/publishing/
This PR switches CI over to using that auth method.
Once this is done, I can invalidate our API tokens, and we can remove the PYPI_TOKEN github secrets from this repo.

ci.yml: use OIDC connect to publish pypi packages

---

typescript/nodejs/README.md
typescript/support/README.md

Minor updates to READMEs
`@mcap/support/nodejs` was an outdated package name. This stuff is not in the `@mcap/support` package anymore but in a separate `@mcap/nodejs` package.
Resolves FG-5991

Update TypeScript READMEs

---

typescript/core/src/Reader.ts

Do not create a new TextDecoder for every record
Massively improves read performance by avoiding unnecessary creation / cleanups of TextDecoders.
Before:
```
[Summary]:
ticks  total  nonlib   name
6600    7.2%   46.1%  JavaScript
7693    8.4%   53.8%  C++
21411   23.3%  149.6%  GC
77489   84.4%          Shared libraries
16    0.0%          Unaccounted
```
After (Notice the drop in GC time):
```
[Summary]:
ticks  total  nonlib   name
3950   10.1%   60.7%  JavaScript
2555    6.6%   39.2%  C++
549    1.4%    8.4%  GC
32426   83.3%          Shared libraries
5    0.0%          Unaccounted
```

Do not create a new TextDecoder for every record

---

website/docusaurus.config.js

Add Slack link to website header.
Rationale: Make it easier to find.

Website: Add Slack link to header

---

website/docs/spec/index.md

Fixes internal links in https://mcap.dev/spec
URLs like https://mcap.dev/spec#data-end-op0x0F are incorrect; they should be lower-case (like https://mcap.dev/spec#data-end-op0x0f).
Noticed on the live website.

Fix internal links in spec index.md

---

website/docs/guides/getting-started/ros-2.md

Moves the `ros2 bag convert` instructions for converting ROS 2 bags to the top. This is the better-supported method and we should be pointing users to it first.

docs: prioritize converting db3 files with ros2 bag convert

---

go/ros/bag2mcap.go
go/ros/bag2mcap_test.go

Prior to this commit, if mcap convert got two ROS1 connections with the same schema but different topic, it would write two schema records.
In this situation only one schema record is needed, as long as the type and the md5 sum are aligned.

CLI: Fix schema deduplication in mcap convert

---

go/mcap/indexed_message_iterator.go
go/mcap/reader_test.go

Prior to this commit, when using the "metadata callback" feature of the indexed message iterator, the reader would mistakenly interpret a byte as a "Token" rather than an "OpCode", causing the parsing of record types to get confused.
This wasn't surfaced in the CLI metadata merging support because that uses the unindexed iterator, which is not affected.
This commit fixes the bug and adds a test for both cases.

Go: Fixes bug in metadata handling for indexed iteration

---

go/mcap/lexer.go

This removes some implicit behavior when using the lexer with a custom decompressor. Prior to this commit, if your custom decompressor exposed a Close() method it would get closed on close of the lexer. After this commit, the caller is responsible for that. The benefit of this is they will be better able to reuse their decompressor if desired.

Go: do not implicitly close custom decompressor in lexer

---

go/mcap/version.go

This sets the CLI version to 1.1.1.
It looks like this will include a couple of fixes:
- #1052 
- #1049

Bump CLI version to 1.1.1

---

README.md

This adds a "Release process" section to the readme. I gleaned these instructions by looking at tags & past commits, but they should be reviewed for accuracy.

Add release process to readme

---

go/ros/ros2db3_to_mcap.go
go/ros/ros2db3_to_mcap_test.go
go/ros/testdata/duplicate_typedefinition/share/ament_index/resource_index/rosidl_interfaces/example_msgs
go/ros/testdata/duplicate_typedefinition/share/example_msgs/msg/Descriptor.msg
go/ros/testdata/duplicate_typedefinition/share/example_msgs/msg/OtherDescriptor.msg
go/ros/testdata/duplicate_typedefinition/share/example_msgs/msg/Parent.msg

FIx `mcap convert` producing ROS2 schemas with duplicate type definitions
It could happen that `mcap convert` produced ROS2 schemas with duplicated subtype definitions if the subtype was included multiple times by various `.msg` files. This PR fixes this by only processing subtypes that haven't been processed before.
Resolves FG-6369

mcap convert: Fix duplicate type definition in ROS2 schemas

---

.vscode/settings.json
go/cli/mcap/cmd/cat.go
go/mcap/reader.go
go/mcap/reader_test.go
go/mcap/version.go

* the go `mcap.Reader` interface now detects unindexed MCAPs and reads messages from them with a linear scan.
Previously when reading a seekable MCAP file with the go library Reader, it would assume that the MCAP was indexed and return no messages if not. After this PR, if an MCAP is not indexed but contains a statistics record, the reader will use the statistics to determine if there are un-indexed messages in the file.
Fixes https://linear.app/foxglove/issue/FG-6441/mcap-cat-doesnt-display-anything-for-unchunked-file

go: reader: fall back to linear scan if statistics show messages outside chunks

---

go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/info_test.go

* CLI: fixes a segfault when an MCAP contains >1024 GiB of data OR results in an greater "data rate" than 1024GiB/s
Previously the `humanBytes` function would segfault when presented with a number > 1024^4.

cli: info does not segfault on large byte values

---

.github/workflows/ci.yml

None
Use @foxglovebot's "personal" fork of homebrew to release CLI versions, rather than the @foxglove org's fork. This allows homebrew automation to amend the PR.
Fixes https://github.com/foxglove/mcap/issues/1063

Use individual fork to submit homebrew updates

---

go/cli/mcap/cmd/cat.go
go/mcap/reader.go
go/mcap/reader_options.go
go/mcap/reader_test.go

Prior to this commit, the before/end parameters forced callers to use int64, when messages really support uint64. Reading uint64-valued timestamps out of MCAP files has never been an issue -- just passing uints as parameters to these options.

Go: support full uint64 range in After/Before read options

---

go/cli/mcap/cmd/cat.go
go/mcap/reader.go
go/mcap/reader_options.go
go/mcap/reader_test.go

Fixed: updated changes from #1068 to be backwards-compatible.
#1068 changed the type of some public API interfaces, which is a breaking change. To avoid needing to publish a v2 library, we deprecate those APIs and introduce new ones that take the new type.

go: make time range options backwards-compatible

---

go/cli/mcap/cmd/merge.go

The merge command documents "none" is an option, but we were not converting that to the appropriate compression string. This led to an "unsupported compression" error when none was supplied. With this commit both "none" and the empty string are accepted.

Support 'none' compression option in merge command

---

website/docs/guides/python/json.md

Ran into this earlier; our python examples are incorrect since https://github.com/foxglove/mcap/pull/629
(website docs PR is at https://github.com/foxglove/website/pull/1347)

Fix (docs): remove mcap0 from python import path

---

go/mcap/lexer.go
go/mcap/lexer_test.go

This adds an "Is" method to ErrBadMagic, in order to make it testable with errors.Is. It also extends the error type with a "location" so that it can indicate whether the magic is at the start or end of the file.

Go: Add Is method to ErrBadMagic

---

typescript/core/package.json
typescript/core/src/ChunkCursor.ts
typescript/core/src/McapIndexedReader.test.ts

@mcap/core: fixed an error when reading topics that were only present in some of the file's chunks.
Fixes #1147, a regression which I believe was caused by #1037. Calling `loadMessageIndexes()` is supposed to guarantee that `#orderedMessageOffsets` is set.

@mcap/core: Fix error when skipping chunks

---

python/Pipfile
python/Pipfile.lock
python/mcap-protobuf-support/mcap_protobuf/decoder.py
python/mcap-protobuf-support/setup.cfg

Minimum protobuf version for `mcap-protobuf-support` would move from `3.8` to `4.25`
Move from `MessageFactory` to `GetMessageClassesForFiles` to remove this warning (adds a lot of noise to our logs):
```
UserWarning: MessageFactory class is deprecated. Please use GetMessageClassesForFiles() instead of MessageFactory.GetMessages(). MessageFactory class will be removed after 2024.
return factory.GetMessages(
```
This would require setting the minimum version for `mcap-protobuf-support` to 4.25. Seems like they fixed [this bug](https://github.com/protocolbuffers/protobuf/issues/12047) in 4.25, which would also simplify the version requirements.
**Note**: I didn't update the library version, but if you all accept this change, I'd assume those would also need to be updated.

Remove deprecated MessageFactory in mcap-protobuf-support

---

.github/workflows/ci.yml
.gitignore

None
This adds a provenance attestation to the published package so consumers can verify that the package was built on GitHub Actions:
- https://github.blog/2023-04-19-introducing-npm-package-provenance/
- https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
The package will appear like this on npm:

typescript: Add provenance attestation when publishing to NPM

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

API getters to return the Attachments mapped with name from the mcap files using C++ API
</td><td>

CPP: Attachements Index getter API to return the Attachments

---

website/README.md
website/docusaurus.config.js
website/modifySvgoConfigInPlace.js

none
As described in https://github.com/facebook/docusaurus/issues/8297, the default webpack config for docusaurus has svgo configured to replace `id` attributes with simple incrementing characters like `"a"`, `"b"`, etc. This leads to ID conflicts between logos and incorrect clipping behavior.
This PR modifies the underlying webpack config to disable changes to ID attributes.
Note that on mac, I was only able reproduce the visual clipping issue in Safari; FF and Chrome seemed to ignore the incorrectly duplicated IDs .
</td><td>

address SVG logo issue

---

python/examples/raw/reader.py

Fixed python raw example topics to match.
In the following example code: https://github.com/foxglove/mcap/tree/main/python/examples/raw
the topic specified in the writer (`"sample_topic"`) did not match the topic specified in the reader (`"/diagnostics"`). This led to the reader not being able to read the message that was written by the writer.
I have manually tested that this example now works.
The reader printed out nothing.
</td><td>
The reader prints out the message written by the writer.

fix python example raw reader topic to match writer

---

go/cli/mcap/utils/ros/json_transcoder.go
go/cli/mcap/utils/ros/json_transcoder_test.go

`mcap cat` is not reading `uint64` ros1 msgs  properly
Super minor, but looks like the `JSONTranscoder` for `ros1msg` is only reading 4 bytes for the `uint64` type.

[go/cli] Fix uint64 bug in `mcap cat`

---

go/cli/mcap/cmd/cat.go

This changes the cat command to do a log-time order scan when it is able to use the index (e.g seekable reader).
This was the intent of the existing code (there is no other reason for it to try to use the index), but it was not supplying both necessary parameters.

CLI: scan in log time order when using index

---

go/mcap/version.go
go/mcap/writer.go
go/mcap/writer_test.go

- Changed: reduced memory footprint of writer by removing an uneccessary chunk buffer.
We are unneccessarily copying the entire compressed chunk into an internal buffer before writing it out - this increases the memory footprint of an mcap writer by the size of a compressed chunk. This isn't too important usually, but when you're running an application that writes 200 MCAP files at once, those 4MB buffers can add up.
This PR removes that chunk buffer and instead uses the `writer.msg` scratch buffer to marshal only the "header" of the chunk. This is all fields of the chunk record besides the compressed data.
This PR also adds a benchmark to demonstrate the memory saving. This benchmark is similar to the existing WriterAllocs benchmark, but:
- we allocate 100 writers and write the nth …

go: reduce memory footprint of writer

---

website/docs/spec/index.md

Prior to this commit, the wording of the spec implied that only channel, schema, and message records are allowed in chunks. This could lead tooling implementers to validate that assertion.
This is inconsistent with our support for extensible record types. Users should be able to put custom records in chunks as well, and readers that parse chunks should ignore unrecognized records rather than error on them.

spec: Clarify legal contents of chunk records

---

go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/sort.go
go/cli/mcap/cmd/sort_test.go

- fixed: `mcap sort` would rewrite the schema and channel for every message in the output file. This is fixed.
</td><td>

cli: sort does not duplicate channels and schemas on every message

---

go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/doctor_test.go
website/docs/spec/index.md

- Added: `mcap doctor` now warns if a schema or channel record is duplicated in the data section. Some writers do this and it wastes space, though reading still works.
- Added: `mcap doctor` now prints an error if an MCAP contains messages in indexed chunks where their channel and schema information are not duplicated in the summary section. This is required by the spec: https://mcap.dev/spec#chunk-index-op0x08
Spec updated to clarify what channels and schemas must be repeated in the summary section.
</td><td>

doctor: warn on duplicate matching schemas and channels

---

website/docs/guides/cpp/protobuf.md

`Protobuf`->`protobuf`
None
One of these versions compiles, the other does not.

Fix capitalization error on protobuf wiki page

---

cpp/examples/protobuf/dynamic_reader.cpp
website/docs/guides/cpp/protobuf.md

protobufs allocated with `New()` must be `delete`d later.
None
Leaks
</td><td>
Doesn't leak (leaks less?)

Stop example protobuf code from leaking

---

website/docs/spec/registry.md

Clarifying that `--include_imports` is necessary. Adding this flag ensures all dependencies are also included in the binary schema.

Clarify instructions for generating binary protobuf schemas using protoc

---

go/mcap/indexed_message_iterator.go

- Fixed: if reading an MCAP file written with chunk index records but no message index records, the go MCAP reader would mistakenly yield no messages.
- Fixed: the indexed MCAP reader would occasionally read too many bytes when reading a chunk.
None.
Right now the go indexed reader does not rely on message index records for anything except to check if a chunk contains messages for that topic. This is incorrect - if a chunk index does not contain message index offsets, it can mean either:
- there are no messages in this chunk
- message indexes are not available for this chunk
See the spec: https://mcap.dev/spec#chunk-index-op0x08
- When resizing the chunk buffer between chunk reads, the reader grows the chunk buffer by a multiple of the new chunk size if it's not big enough. However, it …

go: reader: read files with chunk indexes but not message indexes correctly.

---

go/mcap/version.go

increasing the version number so we can tag a new go version.

go: bump version to v1.4.1

---

rust/src/read.rs

RawMessage fields are now public
None
Currently the `RawMessageStream` is useless because the API does not expose the fields of the `RawMessage` struct. To solve this issue the fields of `RawMessages` are now marked as `pub`.
This PR is the same as https://github.com/foxglove/mcap/pull/934

rust: Make RawMessage fields public

---

typescript/examples/validate/scripts/validate.ts

The validate example was incorrect for ros2msg/cdr channels, and it was also only checking the message encoding and not the schema encoding.

validate: check both message encoding and schema encoding

---

go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/metadata.go
go/cli/mcap/utils/utils.go

Fix: table output from list commands supports wide columns such as large amounts of metadata
None
Previously, listing the metadata for an mcap file with many (>64kb) key/value pairs failed silently.
The Scanner used in the table formatter has a buffer limit of 64kb, and the error result was being ignored. This removes the scanner entirely from most table output. It was introduced to trim leading whitespace from lines, but the formatter accepts other options to make this happen.
I've given the info command its own formatter, which I think is appropriate because it's formatting data differently, even including tabs in its row data. The scanner's error result is now checked, though we shouldn't see this in practice for `mcap info`.
`mcap …

Fix table output with wide columns

---

cpp/README.md
website/docs/guides/cpp/cmake.md

Add a page to `website` with the guide on how to install MCAP with Cmake.
This follows conversation from https://foxglove.slack.com/archives/C02H1JXG3C3/p1719462475680899

add page with guide to install mcap with cmake

---

cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl

Remove unused `startTime_` and `endTime_` members of `McapReader` that were initialized and never used.
None
This is fairly self evident - if the code compiles it should be the correct change.

Remove dead members in McapReader

---

.github/workflows/ci.yml
go/.golangci.yaml

None
None
This upgrades the version of `golangci-lint` to the latest version, and removes three deprecated linters, which now error when included because they are completely unused: https://github.com/foxglove/mcap/pull/1192#issuecomment-2252886768.

Update go linter

---

.vscode/settings.json
rust/src/write.rs
rust/tests/message.rs

On very memory-constrained systems like microcontrollers, the overhead of storing all the chunk offset data in memory until the end of the file can be significant. To avoid that, we instead write all Channel, Schema, and Message data directly as records rather than using chunks, and rely on the reader (or an intermediate ingestion process) to generate the index information.
The rust library now (optionally) supports writing unchunked MCAP files for decreased memory footprint.
None
In our internal testing, storing chunk data required >40KB of memory for several-minute logs, which is a lot for an embedded system with only 300KB of RAM total. Notably, this grows without bound during the test, since the offsets and data about all chunks needs to be stored until the end of the log when it will …

rust: Support writing without chunks

---

go/mcap/indexed_message_iterator.go
go/mcap/version.go

- Changed: when attempting to read a corrupt MCAP using using the index, the reader will return an ErrBadMagic instance rather than a bare Error.
None.
it's useful to be able to tell this error apart from errors that might result from i/o, but right now there is no simple way to determine this using `errors.Is`. This PR gives the error a publicly known type, so that callers can check for it.
</td><td>

go: return a bad magic error in check when parsing summary

---

README.md

We have decided to remove the Contributor License Agreement (CLA) from MCAP and other Foxglove open source projects. The project remains MIT licensed, but we no longer require an additional copyright grant from contributors 🎉. 
Per the [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license), submitted pull requests are licensed under the same terms (MIT).

Remove CLA comment from readme

---

typescript/benchmarks/bench.ts
typescript/benchmarks/package.json

- TS_NODE_TRANSPILE_ONLY=true
- Use v8 heap stats instead of memory usage (isolate vs process heap)
- Baseline before each bench iter and tracking delta
```
McapStreamReader
3.01±0.08 op/s  Heap Used: 268.92±3.81 MB/op    Heap Total: 297.93±4.13 MB/op   ArrayBuffers: 213.39±2.40 MB/op
McapIndexedReader
2.13±0.01 op/s  Heap Used: 284.31±3.36 MB/op    Heap Total: 316.23±1.45 MB/op   ArrayBuffers: 107.06±0.00 MB/op
McapIndexedReader_reverse
2.14±0.02 op/s  Heap Used: 280.16±3.09 MB/op    Heap Total: 315.45±0.79 MB/op   ArrayBuffers: 107.06±0.00 MB/op
McapStreamReader
3.44±0.03 op/s  Heap Used: 51.80±12.44 MB/op    Heap Total: 42.89±11.53 MB/op   ArrayBuffers: 112.95±6.87 MB/op
McapIndexedReader
2.16±0.01 op/s  Heap Used: 70.75±2.55 MB/op     Heap Total: 60.15±2.89 MB/op    ArrayBuffers: …
```

perf(ts): denoise baseline mem usage

---

rust/Cargo.toml
rust/benches/reader.rs

Benches MessageStream on 1M messages uncompressed/zstd/lz4.
```
mcap_read/MessageStream_1M_uncompressed
time:   [67.954 ms 68.277 ms 68.946 ms]
thrpt:  [14.504 Melem/s 14.646 Melem/s 14.716 Melem/s]
mcap_read/MessageStream_1M_lz4
time:   [337.77 ms 344.16 ms 350.76 ms]
thrpt:  [2.8510 Melem/s 2.9056 Melem/s 2.9606 Melem/s]
mcap_read/MessageStream_1M_zstd
time:   [381.62 ms 384.54 ms 388.35 ms]
thrpt:  [2.5750 Melem/s 2.6005 Melem/s 2.6204 Melem/s]
```

perf(rust): add MessageStream benches

---

rust/Cargo.toml
rust/src/read.rs

To avoid reallocs as decompressors write into them. Simple 4-line change that boosts decompressed throughput by +40-50%
```
mcap_read/MessageStream_1M_uncompressed
time:   [66.406 ms 66.638 ms 66.810 ms]
thrpt:  [14.968 Melem/s 15.006 Melem/s 15.059 Melem/s]
change:
time:   [-4.2425% -3.4304% -2.6572%] (p = 0.00 < 0.05)
thrpt:  [+2.7297% +3.5523% +4.4305%]
Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
mcap_read/MessageStream_1M_lz4
time:   [223.21 ms 224.45 ms 225.67 ms]
thrpt:  [4.4313 Melem/s 4.4554 Melem/s 4.4801 Melem/s]
change:
time:   [-36.047% -34.784% -33.497%] (p = 0.00 < 0.05)
thrpt:  [+50.370% +53.337% +56.364%]
Performance has improved.
mcap_read/MessageStream_1M_zstd
time:   [274.52 ms 276.51 ms 278.58 ms]
thrpt:  [3.5896 …
```

perf(rust): prealloc decompression buffers

---

typescript/core/src/ChunkCursor.ts
typescript/core/src/McapIndexedReader.ts
typescript/core/src/McapStreamReader.ts
typescript/core/src/McapWriter.test.ts
typescript/core/src/Reader.ts
typescript/core/src/StreamBuffer.test.ts
typescript/core/src/StreamBuffer.ts
typescript/core/src/parse.ts

Reverts foxglove/mcap#1212
This broke streaming in Foxglove app. Until we can investigate we need to put the library back to a working state.

Revert "perf(ts): reuse Reader whilst parsing records"

---

.github/ISSUE_TEMPLATE/config.yml
python/mcap-protobuf-support/README.md
python/mcap-ros1-support/README.md
python/mcap-ros2-support/README.md
typescript/browser/README.md
typescript/core/README.md
typescript/nodejs/README.md
typescript/support/README.md
website/docusaurus.config.js

Updating references from community slack to community discord.
None
* Links updated to point to https://foxglove.dev/chat
* "Slack channel" etc. references updated to "Discord community" etc.

Updating references & links from slack to discord

---

python/mcap/mcap/writer.py

None
None
It wasn't obvious what format `Writer.add_message` expects for `log_time` and `publish_time` argument but I've figure out that it's nanoseconds since the epoch and decided to update the docstrings so those that come after me don't have to guess.

docs: specify units for `log_time` and `publish_time`

---

.github/workflows/ci.yml
rust/Cargo.toml
rust/benches/reader.rs
rust/examples/common/serialization.rs
rust/examples/conformance_reader.rs
rust/examples/conformance_reader_async.rs
rust/src/lib.rs
rust/src/read.rs
rust/src/records.rs
rust/src/tokio.rs
rust/src/tokio/lz4.rs
rust/src/tokio/read.rs
rust/src/tokio/read_exact_or_zero.rs
rust/src/write.rs
rust/tests/attachment.rs
rust/tests/metadata.rs
tests/conformance/scripts/run-tests/runners/RustAsyncReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/index.ts

- rust: switches the LZ4 compression dependency from `lz4_flex` to `lz4-rs`. This moves us from using a pure-rust lz4 implementation to C bindings. I believe this is worthwhile because `lz4_flex` does not support LZ4 "high compression mode". The practical reason for doing so in this PR is that `lz4_flex` does not expose interfaces that make it easy to build an AsyncRead adapter for it, but `lz4-rs` does.
- rust: Adds structs to read MCAP data asynchronously in a linear stream. 
- Check generated rust docs for review.
Adds an async `RecordReader`implementation, for reading MCAP data asynchronously. This is an optional feature, named `tokio`. I chose this feature flag name and this module name because this functionality is tied heavily into the Tokio ecosystem. If at some point we rebuild …

rust: add async reading functionality

---

go/mcap/indexed_message_iterator.go
go/mcap/reader_test.go

- if a file contains offsets that point outside of file bounds, the Go indexed reader implementation will return `mcap.ErrBadOffset` when attempting to use them.
None.
There are files being uploaded to Foxglove that have invalid offsets inside them - these cause errors in `io.Seek`, which can't be told apart from true IO errors at the moment. This means if a read fails, we can't tell if it's because of a corrupt file or flaky I/O. This PR lets us disambiguate by returning a specific error from the library.
</td><td>

go: indexed message iterator: guard against bad offsets in file

---

cpp/mcap/include/mcap/internal.hpp

Fix for possible undefined behavior in the cpp mcap reader.
None
- We discovered undefined behavior in the `mcap::ParseByteArray(..)` when was running `Rosbag2` tests with `UBSAN` (Undefined Behavior Sanitizer). In particular tests from the https://github.com/ros2/rosbag2/blob/rolling/rosbag2_cpp/test/rosbag2_cpp/test_local_message_definition_source.cpp
UBSAN was pointing ou to the `std::memcpy(output->data(), data + 4, size);` 
- According to the https://en.cppreference.com/w/cpp/string/byte/memcpy If either dest or src is an invalid or null pointer, the behavior is undefined, even if count is zero.
After a comprehensive analysis, we found that we have a null pointer in dest, and the count is zero in std::memcpy(..) when the message definition was not found and was recorded with empty …

cpp: Fix for undefined behavior in mcap::ParseByteArray(..)

---

cpp/mcap/include/mcap/writer.inl

Don't clear channels on writer close(). This matches the behavior schemas has, allowing for stable ids after closing and opening a new file with the same reader. See https://foxglove.slack.com/archives/C02H1JXG3C3/p1720827358364829?thread_ts=1720825408.044619&cid=C02H1JXG3C3
Alternatives to this involve more bookkeeping on the recorder implementation side to re-register all schemas/channels on split.
None
Manual testing, using Basis. YMMV.
</td><td>

Don't clear channels on writer close()

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

Bump version to 1.4.1. Changes include:
- #1239 
- #1199

cpp: bump version to 1.4.1

---

cpp/mcap/include/mcap/writer.hpp

Typo fix in the C++ code documentation
None
See comment edit

[C++] Fix typo in noMessageIndex docs

---

cpp/mcap/include/mcap/writer.inl

- C++ `McapWriter::terminate()` now clears the `writtenSchemas_` set, fixing serialization of `Schema` records after calling `close()` then `open()`. Fixes #1258

c++: Clear writtenSchemas_ in terminate()

---

typescript/browser/package.json
typescript/nodejs/package.json
typescript/support/package.json
yarn.lock

TypeScript: Added missing dependencies on `tslib`
None
Fixes #1262
When `importHelpers` is true in tsconfig.json (as it is by default with `@foxglove/tsconfig`), `tslib` must be a dependency.

Add missing tslib dependencies

---

go/cli/mcap/cmd/attachment.go
go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go

CLI: `mcap add attachment` accepts RFC3339-formatted dates to specify the log and creation times for the new attachment.
CLI: `mcap filter` accepts RFC3339-formatted dates for start and end times.
None.
Adds the ability for users to specify a date when filtering MCAP files, or adding attachments.
I did a quick pass to see if there are any other arguments where we accept a date or date-like value, I can't see any more.

CLI: accept RFC3339-formatted dates in relevant arguments

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/conanfile.py

- Added: added a `flush()` method to `IWritable` to flush any buffered bytes to the underlying writer. This is optional for any external implementations to implement, and defaults to a no-op.
- Changed: After writing a chunk, the McapWriter will call `flush()` on the underlying writer. This ensures that any completed chunk does not get held up in an internal buffer while the next chunk is being constructed.
See new docstring on `flush()`.
Adds a virtual function to the `IWritable` interface to flush it, with a default no-op implementation. I don't really know the right policy for un-chunked files, but my current opinion is that we can leave that to the caller - they might call flush every few seconds, or every few messages.
I don't consider this a breaking change. This is almost certainly …

C++: flush underlying writer after every chunk write

---

go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/filter_test.go

- Fixed: the `-e` argument to `mcap filter` will be interpreted properly again.
None.
The last change to `filter` mistakenly swapped the `nanos` and `seconds` arguments to `parseTimestampArgs` for the filter end time.
- Tested `mcap filter -s 10 -e 1000` manually, previously failed, now works.
Fixes: #1268

filter: fix end second parsing

---

.github/workflows/ci.yml

GitHub charges for LFS bandwidth between GitHub and GitHub Actions. Therefore we should remove unnecessary usage of LFS in CI.
Blocked by https://github.com/foxglove/mcap/pull/1272 because yarn plugins were stored in LFS

Remove unnecessary usage of LFS in CI

---

website/src/components/McapRecordingDemo/McapRecordingDemo.tsx
website/src/components/McapRecordingDemo/Recorder.ts
website/src/components/McapRecordingDemo/videoCapture.ts

Like https://github.com/foxglove/mcap/pull/1275 but for AV1.

Add AV1 encoding to web demo if supported

---

go/mcap/reader_test.go
python/mcap/tests/test_reader.py
testdata/bags/demo.bag
testdata/mcap/demo.mcap

None
None
Use smaller and simpler `demo.bag` and `demo.mcap` files.
Fixes: FG-9552

Use smaller testdata files

---

rust/Cargo.toml
rust/src/lib.rs
rust/src/sans_io/decompressor.rs

rust: make sure structs are Send
None
This PR makes sure that all MCAP readers and writers can be sent between threads. This is mainly just adding `Send` to the `Decompressor` trait, but it also adds compile time assertions to make sure we don't regress.
readers are not `Send`
</td><td>
readers are now `Send`

rust: make interfaces Send

---

rust/Cargo.toml
rust/src/lib.rs
rust/src/write.rs
rust/tests/attachment.rs

rust: support writing attachments in multiple chunks
None
This change supports writing large attachments to MCAP files without the need to load them into memory.
Currently, in order to write an attachment, you need to load the entire file into memory, create an `Attachment` record, then use that with the `attach` method on the writer.
This means that it is not possible to attach files when the file exceeds the available memory on the computer.
This change adds The methods `start_attachment`, `put_attachment_bytes` and `finish_attachment` for interactively writing an attachment without needing to buffer the file in memory. It looks like this:
```rust
let writer = Writer::new(..);
let attachment_length = ..;
let header = AttachmentHeader { .. };
writer.start_attachment(attachment_length, …
```

rust: write attachments in parts

---

python/mcap/mcap/_chunk_builder.py

None
None
In the Python implementation of `ChunkBuilder.reset()`, the `self.buffer` object is recreated but never actually referenced. This PR removes the unused `self.buffer` variable to simplify the code.
I manually ran the following examples without encountering any errors:
```
python3 python/examples/jsonschema/pointcloud_csv_to_mcap.py python/examples/jsonschema/bus.csv
python3 python/examples/protobuf/image_example.py ptoro_image.mcap
python3 python/examples/protobuf/writer.py proto.mcap
python3 python/examples/raw/writer.py raw.mcap
```
Additionally, I ran:
```
mcap doctor out.mcap
mcap doctor ptoro_image.mcap
mcap doctor proto.mcap
mcap doctor raw.mcap
```
All checks passed without issues.

python: remove unused buffer

---

website/src/components/McapRecordingDemo/McapRecordingDemo.tsx
website/src/components/McapRecordingDemo/Recorder.ts
website/src/components/McapRecordingDemo/videoCapture.ts

Same as #1275 & #1278, this time for VP9. The number of checkboxes is getting out of hand:

Add VP9 encoding to web demo if supported

---

python/mcap/mcap/reader.py

None
* Updated the Python docstrings for the MCAP readers to label the `end_time` parameter as an exclusive bound
* The documentation on [this page](https://mcap.dev/docs/python/mcap-apidoc/mcap.reader#mcap.reader.McapReader.iter_decoded_messages) will also be updated
According to the documentation [here](https://mcap.dev/docs/python/mcap-apidoc/mcap.reader#mcap.reader.McapReader.iter_decoded_messages), the iterator should exclude messages that were logged before `start_time` or after `end_time` (i.e. both inclusive bounds). However, the implementation also excludes messages published at the same time as `end_time` (making it an exclusive bound). The documentation has been updated to match the implementation.
This discrepancy in the Python package is only happening in …

Update docs to match exclusive end_time implementation

---

go/cli/mcap/cmd/filter.go

Fixed a bug in `mcap recover` which would produce an invalid file when redirecting stdout to a file.
None
Status message now goes to stderr instead of stdout.
Also fixed another nearby line which looked wrong, it was using Fprintln with `%w` but Fprintln doesn't accept format strings. https://pkg.go.dev/fmt#Fprintln

mcap recover: print status message to stderr instead of stdout

---

rust/Cargo.toml
rust/src/sans_io/read.rs

- Rust: fixed a bug where a reader not reading the exact amount required into the LinearReader might cause the internal buffer to grow unbounded.
</td><td>

rust: LinearReader: reclaim dead space when possible

---

rust/Cargo.toml
rust/src/sans_io/read.rs
rust/tests/data/break_zstd_decompression.mcap
rust/tests/data/zstd_chunk_with_padding.mcap

- rust: fixed case where a compressed chunk with padding bytes added by the compressor at the end would break decompression.
None.
When MCAPs are written, the compressor may insert padding bytes at the end of a compressed block after all useful data bytes are written. This means that when the decompressor is reading messages out, it will have decompressed all message bytes out of a compressed chunk _before_ it reaches the end of the compressed data. Right now, the rust MCAP library will see that there is more unused data in the compressed chunk, try to decompress another message, but get no output from of the decompressor when it tries.  Right now this causes the reader to loop infinitely. This PR adds a file to LFS which triggers this condition and fixes it. …

rust: read: handle padded compressed chunks properly

---

.github/workflows/ci.yml
rust/Cargo.toml
rust/benches/reader.rs
rust/examples/common/conformance_writer_spec.rs
rust/examples/conformance_writer.rs
rust/src/lib.rs
rust/src/read.rs
rust/src/sans_io/read.rs
rust/src/write.rs
rust/tests/handles_time0_messages.rs
rust/tests/message.rs

- adds `id` members to the crate::Channel and crate::Schema structs.
- refactored and separated `Writer::add_channel` into two methods, `Writer::add_schema` and `Writer::add_channel`.
In docstrings, please review if not clear.
When a message reader recieves schema and channel information, the schema and channel IDs in the MCAP are hidden from them.  This PR adds those so that readers can observe ID information.
Additionally, this PR updates the Writer interface in these ways:
1. The `add_channel(Channel)` method is replaced with `add_channel(schema_id, topic, message_encoding, metadata)`. This was done because the Channel struct now contains a channel ID, and to continue to use it would force the user to come up with their own channel ID before calling this function. 
2. An …

rust: Channel and Schema structs have IDs

---

cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/unit_tests.cpp

Close chunks when big messages are written to isolate them, leading to much better read performance when going over small-message channels since those isolated chunks can be skipped over entirely.
None
A very common situation is to have a few topics with very large messages (images, point clouds, etc.) and many topics with very small (and frequent) messages (state, transforms, statuses, etc.). When writing all those into a single ("merged") mcap file, it naturally leads to chunks typically containing a series of small messages and ending with one big message which fills the rest of the chunk and "closes" it. The result of this is that nearly all chunks are "mixed" (i.e., messages from all channels appear in each chunk). During playback / reading, some of the client code (e.g., C++) …

Preemptively close chunks before big messages to isolate them

---

typescript/core/src/ChunkCursor.ts
typescript/core/src/McapIndexedReader.test.ts

typescript: support chunk indexes with empty message index
None
When a chunk contains no messages, the corresponding [ChunkIndex](https://mcap.dev/spec#chunk-index-op0x08)'s message index is empty. Prior to this PR, the typescript lib threw an exception when a chunk index with an empty message index was encountered. 
This PR changes this to no longer throw when such a chunk index is encountered. If the message index is empty, the internal method `#getSortTime` will fallback to the chunk index' start time which is `0n` and everything works as expected.
https://github.com/foxglove/mcap/blob/e5c9da312727063194e52e84e2b71a7cfaa66f6d/typescript/core/src/ChunkCursor.ts#L228-L229
Note: We could change the `McapIndexedReader` to exclude such chunk indexes from its internal heap, but I believe …

typescript: support chunk indexes with empty message index

---

.github/workflows/ci.yml

None
None
See also https://github.com/foxglove/schemas/pull/158.
> Running a publish to TestPyPI immediately followed by a publish to the "real" PyPI triggered an error due to a file already existing. The workaround recommended in https://github.com/pypa/gh-action-pypi-publish/issues/283#issuecomment-2499296440 is to set `attestations: false` on the TestPyPI publish.

fix pypi publishing

---

rust/src/io_utils.rs
rust/src/write.rs

Add an `into_inner()` method on the Rust writer to get back the underlying stream.
https://linear.app/foxglove/issue/FG-9969/[rust-sdk]-cant-close-mcap-writer
Some I/O errors only show up when the output file is closed. This change allows users to check for such errors.
Fixes: FG-9969

Add into_inner() on Rust writer

---

python/mcap/mcap/_message_queue.py
python/mcap/mcap/reader.py
python/mcap/tests/test_message_queue.py

Significantly increases the performance of iterating through an MCAP file in insertion order.
None. (internal only)
I used `iter_messages(log_time_order=False)` since my application doesn't care about message order, expecting it to perform better than `log_time_order=True` (the default). However I noticed that my application took _17 minutes_ to iterate through 3.5 million MCAP messages. It took 32 seconds with `log_time_order=True`. 
The previous message queue implementation used a `list` as a FIFO queue, which has poor performance as `pop(0)` will copy the list every time an item is evicted. After changing the implementation to use a `deque`, `log_time_order=False` took 15 seconds.
Here's code for a minimal performance test. Note that the mcap file has ~3.5 million messages.
```python …
```

fix(python): use deque for insert-order message queue

---

rust/Cargo.toml

None
None
Bump the Rust version to 0.14.1 to release the `into_inner` changes.

rust: release version 0.14.1

---

rust/examples/conformance_writer.rs
rust/src/io_utils.rs
rust/src/write.rs

- Added: rust writeOptions now include `calculate_*_crc[s]` options to enable or disable CRC calculation.
Check docstrings.
CRC calculation can have a meaningful impact on CPU load and throughput, and is not appropriate for some use-cases. 
</td><td>

writer: add options to switch off CRC calculation

---

rust/src/records.rs
rust/src/write.rs

fixed: don't allocate buffer for every `Message` in Rust
None
Removes the temporary vec used to write out the message header every message.
I would like to clean up all of these temporary buffers in `write_record` since the serialized length should be able to be calculated dynamically. However this is the one that is called most frequently so it makes sense to do this first.

rust: avoid allocating for message header

---

go/mcap/indexed_message_iterator.go

Prior to this commit, the indexed iterator did not rule out chunks based on topic specification, which meant it still opened chunks when no topics would match. With this change the tool does less IO when there is no matching data.

Speed up indexed iterator on negative search by topic

---

.github/workflows/ci.yml
rust/Cargo.toml
rust/examples/conformance_writer.rs
rust/src/read.rs
rust/src/write.rs

- Fixed: fixed a bug where when writing messages using `mcap::Writer::write(&Message{...})`, introduced in #1297 . Writing messages on separate channels with identical channel data would cause channel data for some channels not to be written to the MCAP, resulting in an invalid MCAP.
None.
MCAP as specified allows a 1:N relationship between channel content and channel IDs. This is intentional - there may be multiple sources publishing the exact same topic, and the output MCAP can and should contain one channel per publisher, not per topic.
#1297 introduced the use of a bimap to track the relationship between channel / schema IDs and their content. however, I overlooked at the time a key constraint of the bimap implementation, in that all values on the left and right side are unique.
This …

rust: fix removal of identical channel data

---

go/cli/mcap/cmd/cat.go

This adds support to the `mcap cat` command for multiple input files. Multiple files can be directly supplied, like
mcap cat file1.mcap file2.mcap
or, the list of files may be auto-populated by your shell, enabling you to type
mcap cat **/*.mcap

cli: Support multiple inputs in 'cat'

---

rust/examples/conformance_reader_async.rs
rust/src/lib.rs
rust/src/read.rs
rust/src/sans_io.rs
rust/src/sans_io/linear_reader.rs
rust/src/tokio.rs
rust/src/tokio/linear_reader.rs

- Breaking: renamed `mcap::sans_io::read` to `mcap::sans_io::linear_reader`.
- Breaking: renamed `mcap::sans_io::read::ReadAction` to `mcap::sans_io::linear_reader::LinearReadEvent`
- Breaking: renamed `LinearReader::next_action()` to `LinearReader::next_event()`.
- Breaking: renamed `LinearReader::set_written()` to `LinearReader::notify_read()`.
- Breaking: renamed `mcap::tokio::read::RecordReader` to `mcap::tokio::linear_reader::LinearReader`
Changes are reflected in `cargo doc`.
This PR revises the names of functions and structs exposed from the `sans_io` module, because they're badly named as-is and we need to fix this now before we add more to this module.
Specifically:
1. `ReadAction` gets renamed to `LinearReadEvent`. This is because there's no definition of "action" in this …

rust: rename items in linear reader

---

cspell.config.yaml
website/docs/spec/registry.md

[MessagePack](https://msgpack.org/) is a binary encoding similar to CBOR.
Add to the registry how to encode this in MCAP files.

Document MessagePack (msgpack) encoding

---

rust/src/tokio/linear_reader.rs

I just spotted that we zero the buffer with resize and then immediately overwrite it. Using clear + extend is more efficient and is a quick fix with no downside.

Optimize LinearReader::next_record

---

website/docs/guides/cli.md

None
None
This updates the CLI documentation to point to the releases page, filtered for CLI releases. The existing link (`/latest`) may or may not point to a CLI release.

Improve releases link

---

rust/Cargo.toml
rust/examples/mcapcat.rs
rust/examples/mcapcopy.rs
rust/examples/recover.rs
rust/src/lib.rs
rust/src/read.rs
rust/tests/attachment.rs
rust/tests/common.rs
rust/tests/compression.rs
rust/tests/message.rs
rust/tests/metadata.rs
rust/tests/round_trip.rs

Replace (unmaintained) `memmap` dev-dependency with `memmap2`.
None, other than the corresponding doc-comment change in `lib.rs`.
`memmap` has been unmaintained for many years; there has been a RustSec [advisory](https://rustsec.org/advisories/RUSTSEC-2020-0077.html) about this for 4 years. As a dev-dependency this isn't critical, but it seems likely that users of this library will copy/paste example code. Setting a good example for them seems worthwhile.

replace `memmap` with `memmap2`

---

rust/Cargo.toml
rust/src/sans_io/zstd.rs

Upgrade the `zstd` dependency to `0.13`.
None
`zstd 0.11` is about 3 years out of date. Using the same major version as other projects will reduce the need for duplicate dependencies in a cargo workspace.
Notes about the change:
- `ZstdDecoder` will panic on init failure to avoid changing the return type. Note that `DStream::create` already panics on failure.

upgrade to zstd 0.13

---

rust/Cargo.toml
rust/src/write.rs

Make `Writher::with_options` public
None
Makes the `Writer::with_options` method in the Rust library public to easier support setting options.
This also bumps the version to 0.16.0 in preparation to release this and the breaking changes from #1341.
Fixes #1348.

rust: make Wrtier::with_options pub

---

go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go

Ensure channel auto coalescing is deterministic in `mcap merge` 
In the `mcap merge` command, the channel auto coalescing is currently non-deterministic due to the random ordering of iterating over a map in go. This change just sorts the metadata keys before we hash it to ensure for the same channel metadata we always get the same hash.
For example, if trying to merge these to mcaps
```
library:   mcap go v1.7.1; mcap go v1.7.0
profile:
messages:  800
duration:  19.979441843s
start:     2024-07-01T10:23:52.441156385-07:00 (1719854632.441156385)
end:       2024-07-01T10:24:12.420598228-07:00 (1719854652.420598228)
compression:
zstd: [1/1 chunks] [273.00 KiB/36.78 KiB (86.53%)] [1.84 KiB/sec]
channels:
(4) /imu  800 msgs (40.04 Hz)   : sensor_msgs/Imu [ros1msg]
channels: 1
attachments: 0 …
```

go: fix channel auto coalescing in merge

---

.github/workflows/ci.yml
rust/Cargo.toml
rust/benches/reader.rs
rust/examples/conformance_indexed_reader.rs
rust/src/lib.rs
rust/src/read.rs
rust/src/records.rs
rust/src/sans_io.rs
rust/src/sans_io/indexed_reader.rs
rust/src/sans_io/linear_reader.rs
rust/src/sans_io/summary_reader.rs
rust/src/write.rs
tests/conformance/scripts/run-tests/runners/RustIndexedReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/index.ts

- Added: `mcap::sans_io::SummaryReader` and `mcap::sans_io::IndexedReader` structs, which can be used to a) parse out summary information and b) read messages efficiently using that summary information.
See `cargo doc` for usage info.
Adds a sans-io indexed reading implementation, including conformance tests and benchmarks.
The indexed reader is suspiciously faster than MessageStream by quite a bit. I suspect the major difference is that the indexed reader allows the caller to re-use the same buffer for every message yielded, rather than allocating a new one.
Raw `cargo bench` outputs (with changes removed because they compare to the previous run, which is confusing)
```
mcap_read_linear/MessageStream_1M_uncompressed
time:   [165.82 ms 167.64 ms 169.53 ms]
thrpt:  [5.8986 Melem/s 5.9653 …
```

rust: add sans-io indexed reader 

---

.github/dependabot.yml

None
None
Enables Go dependabot updates for the CLI. This should make sure that the CLI has the correct workspace dependency versions without us needing to update our pipelines to update this for us.

allow dependabot to update cli dependencies

---

rust/src/write.rs
website/docs/guides/cli.md

None
This fixes some typographic and capitalization errors in the Rust docs, and simplifies the website CLI releases link (which now matches the readme).

Minor documentation fixes

---

go/mcap/reader.go
go/mcap/reader_test.go
go/mcap/version.go

Changed: refined error message of `UnexpectedTokenError` to not include the full token byte array.
This is useless - in the common case, the unexpected token is garbage, and contains garbage data. A human is not expected to read the byte array.
</td><td>

go: reader: do not report full byte array for UnexpectedTokenError

---

go/cli/mcap/go.mod
go/mcap/go.mod

None
None
Bumps the minimum go versions so that dependabot can update the mcap cli version. It has currently been struggling to do this because the "slices" package is not available in the standard library (it was released in 1.21). https://github.com/foxglove/mcap/network/updates/1002878288
This change sets the minimum version to 1.21 to support it. The workspace version is currently 1.22.5.

bump minimum go version for dependabot

---

rust/Cargo.toml
rust/src/read.rs
rust/src/write.rs

- Changed: the `mcap::writer::Writer::finish()` method now returns a summary of the files' content.
None.
We have a few cases internally where we want to write out an MCAP to some destination, then also track the summary information for that MCAP somewhere else. Cases include:
- log rotation, where we want to track schemas and channels written and would rather not do that externally
- maintaining an external index of MCAP chunks, which we do at Foxglove
- Writing then immediately reading back chunk data without needing to re-parse the just-written summary
This PR enables that by returning a summary from `finish()`.
Note: similar functionality is available from the Go writer, which exposes statistics and indexes as public fields from the Writer struct, see here: …

rust: writer: return summary from finish()

---

cpp/mcap/include/mcap/types.hpp

Add a missing cstdint include that causes a build error with GCC 15.1.1.

cpp: add missing cstdint include (gcc15 build failure)

---

cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.inl
cpp/test/unit_tests.cpp

- cpp: Fix a few bugs related to message-less chunks
None
PR #1291 added an optimization, which caused the behavior reported in issue #1355. The intention of that change was to close a non-empty chunk before writing a message that would overflow the chunk size. It checks whether the chunk is non-empty _after_ writing `Channel` & `Schema` records to the chunk (see: [writer.inl](https://github.com/foxglove/mcap/blob/ba0d926f112ec7fa207c7a7c6d2a4809570db850/cpp/mcap/include/mcap/writer.inl#L550-L557)). Therefore, it's possible to write a chunk that contains no messages.
The writer has a small bug in the metadata that it writes into the chunk index record. The `currentChunkStart_` register is initialized as `MaxTime`, and only updated when a message is added to the chunk. But when writing a …

cpp: Fix bugs related to message-less chunks

---

cpp/examples/CMakeLists.txt
cpp/examples/rotatemcap.cpp
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl
cpp/test/unit_tests.cpp

Fix an issue where re-using a writer leads to schemas appearing in mcap files where they were not used. Documented how to re-use a writer correctly and added an example.
I made changes to the doc comments, how do I deploy those?
There were some issues in terminate() not clearing all the state it needs to, as well as in writing the summary where schemas and channels that don't appear in the file can be written out.
I fixed those issues, added a test for them, added docs for how to re-use a McapWriter safely, and added an example.
Linear ticket: FG-10773

Fix issue with re-using McapWriter

---

website/docs/spec/index.md

None
Is
Clarifies that MCAP strings must be utf-8 encoded. the "should" wording makes it unclear if readers may treat utf-8 strings as errors. Some of our implementations (python, rust) already do, others are more permissive.
I will follow up to set up `mcap doctor` to error on non-utf8 strings.
</td><td>

spec: clarify that strings are utf-8

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

Bump version from 2.0.1 to 2.0.2 based on this PR as a template: https://github.com/foxglove/mcap/pull/1376/files

bump c++ version from 2.0.1 to 2.0.2

---

go/mcap/indexed_message_iterator.go
go/mcap/reader_test.go

go: fixed a bug with InOrder message reading when using additional filters with overlapping chunks.
None
Previously, during `loadChunk()`, `sortingRequired` would only be set to true if the new chunk internally had some messages out of order (or if some messages had been read already?). However, the messages also need to be sorted even if none have been read yet and each chunk is individually ordered, to properly handle overlapping chunks.
Fixed by starting with `sortingRequired = true` and only setting it to false if no message indexes are outstanding. It kinda looks like the existing logic was already supposed to work this way but I'm not totally sure.
Fixes #1374

go: fix iteration edge case with overlapping chunks

---

go/mcap/version.go

- #1385 
None
Bumping version to release #1385

go: bump version to 1.7.3

---

website/docs/guides/getting-started/ros-2.md

Added documentation for using rosbag2 convert with mcap compression.
None
When creating a rosbag with `ros2 bag convert` and this configuration:
```yaml
output_bags:
- uri: out
storage_id: mcap
compression_mode: file
compression_format: zstd
all_topics: true
```
A `out_0.mcap.zstd` file is created, which is unreadable by `ros2 play` -- the file must be first be fully inflated (taking up 4x the original space and long time) and can then be read.
Thanks to a contributor at rosbag2 (https://github.com/ros2/rosbag2/issues/1920) I was able to figure out a working configuration for converting to a compressed rosbag, which involves two separate configuration files:
```yaml
output_bags:
- uri: out
storage_id: mcap
storage_config_uri: mcap_config.yaml
all_topics: true
```
and `mcap_config.yaml` as …

Add information regarding rosbag2 conversion compression

---

rust/src/records.rs

None
None
Deleted unused functions.

chore(rust): delete unused time conversion utilities

---

rust/src/write.rs

This PR adds two new write options:
* `compression_level: u32` – compression level to use for zstd/lz4, or zero to use the default compression level.
* `compression_threads: u32` - number of threads to use for compression, or zero to disable multithreaded compression.
None? Let me know if I need to update docs somewhere.
Prior to this PR, it wasn't possible to set the compression level; the default lz4 and zstd compression levels were used. Now, it's possible to set the lz4 and zstd compression levels.
Prior to this PR, non-wasm targets were forced to use multithreaded zstd compression ([reference](https://github.com/foxglove/mcap/blob/b404e42bd9ca6e9193ae994f7f3d752248ea8b06/rust/src/write.rs#L1368)). Now, it's possible to disable multithreaded compression, or to use a different number …

rust: configurable compression level and threads

---

go/cli/mcap/cmd/doctor.go

the MCAP spec defines strings as valid utf-8, but we don't check that in Doctor (until now).
Doctor would not inspect strings for validity</td><td>
`mcap doctor` on an MCAP file with MCAP strings that are not valid utf-8 will produce an error.

doctor: add check for non-utf8-formatted strings

---

website/docs/spec/index.md

The docs aren't super clear about what "user proposals", "user extensions" or "application extensions" are, and why the opcodes from 0x80 are reserved for this purpose.
I propose we change this to simply say "private records". There is some precedent for this around; PNG defines "private chunks", MP4 defines "private streams" or "private extensions", TIFF defines "private tags". Other formats mention "application" or "custom" data or extensions.

docs: clarify extension record wording

---

rust/Cargo.toml
rust/examples/conformance_reader_async.rs
rust/src/lib.rs
rust/src/records.rs
rust/src/sans_io.rs
rust/src/sans_io/indexed_reader.rs
rust/src/sans_io/linear_reader.rs

- rust: add option to raise an error if a record is above a length limit, rather than potentially allocating too much memory.
See docstrings.
Adds an option the sans-io reader library to limit the length of record yielded from the reader. This protects the user from corrupt data that might otherwise cause the reader to try to allocate huge amounts of address space.
</td><td>

rust: add record length limit option

---

rust/Cargo.toml
rust/src/lib.rs
rust/src/write.rs

- rust: support writing private records
None
This change adds support for a simple `write_private_record` method for writing user-defined private records as per the spec. Since private records may also appear in chunks the method has a boolean "chunkable" flag.
users cannot write records with custom opcodes
</td><td>
users can write private records

rust: support writing private records

---

typescript/core/package.json

Bump the Typescript core package with the `McapStreamReader` unknown record fixes.

typescript: bump core to 2.1.7

---

website/docs/guides/python/protobuf.md

None
Diff
Title.
I got "unused import" when i copy-pasted the example, I assume it's not there for a reason? Feel free to close if deemed noise.

docs: unused import in python protobuf.md example

---

rust/Cargo.toml
rust/src/read.rs
rust/src/sans_io/summary_reader.rs

- Adds a file size check when reading summaries using SummaryReader
None
In most situations where `SummaryReader` is useful, the file size is known in advance. This can be used to greatly improve bounds checking when attempting to allocate buffers or seek. While the `SummaryReader` is somewhat capable of inferring the file size on its own, it does so in a rather hacky way that's susceptible to misuse.
This change adds an explicit file size to `SummaryReaderOptions`, further constrains the bounds checking added in #1407, and adds some unit tests to validate various corner cases.

rust: Add option to summary reader to declare file size

---

rust/Cargo.toml
rust/src/sans_io/summary_reader.rs

- rust: SummaryReader validates magic before footer opcode
None
The SummaryReader currently returns `McapError::BadFooter` for a truncated file, but `McapError::BadMagic` is far more appropriate for identifying truncated files.
This is useful for incorporating the SummaryReader into the agent. See https://github.com/foxglove/data-platform/pull/1982 and specifically https://github.com/foxglove/data-platform/pull/1982/files#diff-14f4b5ab5c91cbb2ed0875adc6fa2362858bb2984513399610f07bec3aaf6624R38-R41.

rust: Validate magic before footer opcode

---

.github/workflows/ci.yml

Added CI support for ARM 32-bit (arm-linux-gnueabihf) cross-compilation.
None
This change extends the CI matrix to include a new build target for 32-bit ARM using `arm-linux-gnueabihf-gcc`. This is useful for testing compatibility with devices running 32-bit ARM Linux, such as Raspberry Pi models or embedded systems, and ensures build correctness across more deployment environments.
Manually validated by verifying package installation (`gcc-arm-linux-gnueabihf`) and confirming CI matrix executes successfully.
CI did not test for 32-bit ARM targets.
</td><td>
CI includes a job with `arm-linux-gnueabihf-gcc` to build for 32-bit ARM.
Fix #1416

ci: Add armv7 build

---

typescript/browser/README.md
typescript/support/README.md

Removed unused `import { open } from "fs/promises";` from the README.md example to improve clarity and avoid confusion in the browser-based usage demonstration.
This PR updates the README.md file in the `@mcap/browser` and `@mcap/support`.
None

Remove unused import of 'open' from README.md example

---

typescript/browser/README.md
typescript/support/README.md

Fix incorrect file extraction example in browser usage guide to handle InputEvent and DragEvent safely.
This PR updates the README.md file in the `@mcap/browser` and `@mcap/support`.
The current README example under “Reading MCAP files in a browser” incorrectly uses:
```typescript
const file = event.dataTransfer.files[0];
```
while claiming to support both InputEvent and DragEvent. This will fail for InputEvent, as it does not have a dataTransfer property, leading to `undefined` or runtime errors.
This PR updates the example to correctly distinguish between DragEvent and InputEvent, ensuring safe and reliable file extraction for users following the guide.
This improves developer experience for those onboarding with `@mcap/browser` and `@mcap/support` by providing a copy-paste-safe, …

fix(readme): correct file input handling in browser example

---

go/cli/mcap/cmd/filter.go
go/cli/mcap/cmd/info.go

This adds information about max chunk size and presence of chunk overlaps to the mcap info output under a new "chunks" entry. When a file is unchunked, this information is omitted.
Also adds a --unchunked switch to `mcap compress`, which is useful for creating unchunked files for testing.

cli: add more chunk info to "mcap info"

---

cpp/README.md
cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/mcap/include/mcap/visibility.hpp
cpp/test/conanfile.py

Proposed as an alternative to https://github.com/foxglove/mcap/pull/1380.
Adds an `#ifndef` guard around the existing definition logic in `visibility.hpp`. This allows application code to determine the meaning of MCAP_PUBLIC directly, if the implementation in `visibility.hpp` doesn't work for them.
</td><td>

cpp: allow application to determine visibility attributes

---

rust/src/read.rs
rust/src/sans_io/indexed_reader.rs
rust/src/sans_io/linear_reader.rs

Fixes some clippy warnings for the new 1.89 release.

rust: fix clippy warnings

---

rust/Cargo.toml
rust/src/chunk_sink.rs
rust/src/lib.rs
rust/src/write.rs

- rust: removed the condition for a panic if a subsequent write failed.
None.
Previously, if we attempted to close a chunk and this failed, the writer would be left in an invalid state, with `self.writer = None`. This is no longer the case. Instead we return an explicit error value for cases where we can no longer write because the underlying file is invalid in an (unknown) state.
</td><td>

rust: do not panic on next write if chunk closure fails
