foxglove/mcap

typescript/package.json
typescript/scripts/bag2proto.ts
typescript/src/McapWriter.ts
typescript/src/index.ts
typescript/typings/protobufjs.d.ts
yarn.lock

Convert a ros1 bag file to a protobuf mcap file.

Add bag2proto script to typescript folder

---

README.md
typescript/package.json
typescript/src/McapReader.ts

Use MCAP project name consistently.

Message Capture -> MCAP

---

.gitattributes
.github/workflows/ci.yml
README.md
docs/specification/README.md
docs/specification/compression/supported-compression-formats.md
docs/specification/diagrams/chunked.png
docs/specification/diagrams/unchunked.png
docs/specification/notes/explanatory-notes.md
docs/specification/profiles/README.md
docs/specification/profiles/ros1.md
docs/specification/profiles/ros2.md
package.json
yarn.lock

Initial draft of MCAP specification.

Add MCAP specification

---

.github/workflows/ci.yml

Move docs lint to a separate CI job

---

typescript/scripts/validate.ts

Fixes validate on indexed files.

Fix validate script to process channel info before readMessages() on indexed files

---

go/libmcap/writer.go
testdata/mcap/demo.mcap

Remove the CRC from channel info to accord with v0.

Remove CRC from channel info

---

typescript/src/v0/Mcap0IndexedReader.test.ts
typescript/src/v0/Mcap0IndexedReader.ts

This will be needed for parsing messages.

typescript: expose schemas from Mcap0IndexedReader

---

.github/workflows/ci.yml
go/Makefile
go/conformance/Makefile
go/conformance/conformance_test.go
go/conformance/go.mod
go/conformance/go.sum
go/conformance/main.go
go/libmcap/indexed_message_iterator.go
go/libmcap/lexer.go
go/libmcap/lexer_test.go
go/libmcap/mcap.go
go/libmcap/parse.go
go/libmcap/reader.go
go/libmcap/reader_test.go
go/libmcap/testutils.go
go/libmcap/unindexed_message_iterator.go
go/libmcap/writer.go
go/libmcap/writer_test.go
go/mcap/cmd/cat.go
go/ros/bag2mcap.go
go/ros/ros2db3_to_mcap.go
testdata/mcap/demo.mcap
tests/conformance/scripts/run-tests/runners/GoStreamedTestRunner.ts
tests/conformance/scripts/run-tests/runners/index.ts

Adds a conformance test runner for go.

Go: Add conformance tests

---

docs/specification/README.md

spec: Allow empty encoding string in Schema record

---

docs/specification/README.md
docs/specification/compression/supported-compression-formats.md
go/libmcap/go.mod
go/libmcap/go.sum
go/libmcap/lexer.go
go/libmcap/lexer_test.go
go/libmcap/mcap.go
go/libmcap/testutils.go
go/libmcap/writer.go
go/libmcap/writer_test.go
go/ros/bag2mcap.go
go/ros/go.mod
go/ros/ros2db3_to_mcap.go
python/mcap/mcap0/stream_reader.py

Prefer ZSTD over LZ4 compression in our application defaults and example code.

Favor ZSTD over LZ4

---

go/.gitignore
go/conformance/Makefile
go/mcap/Makefile
tests/conformance/scripts/run-tests/runners/GoStreamedTestRunner.ts

Puts go binaries in bin directories and gitignores them.

Put go binaries in bin directories

---

cpp/mcap/include/mcap/mcap.hpp
cpp/mcap/include/mcap/mcap.inl
cpp/test/CMakeLists.txt
cpp/test/streamed-writer-conformance.cpp
cspell.config.yaml
tests/conformance/scripts/run-tests/runners/CppStreamedReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/CppStreamedWriterTestRunner.ts
tests/conformance/scripts/run-tests/runners/index.ts

- Don't create Chunk records when noChunking=true
- Fix Attachment CRC calculation
- Basic C++ write conformance testing

[C++] Write conformance tests, fixes

---

README.md
typescript/README.md

Some README cleanups ahead of our announcement post.

link to individual language readmes from main readme

---

typescript/mcap/src/v0/Mcap0IndexedReader/index.test.ts
typescript/mcap/src/v0/Mcap0IndexedReader/index.ts

Fixed a bug in TypeScript Mcap0IndexedReader where summary CRC checking would fail if the IReadable's buffers were being reused between read() calls.
Split from https://github.com/foxglove/mcap/pull/219

Fix buffer reuse in TS indexed reader for summary CRC calculation

---

go/mcap/lexer.go
go/mcap/lexer_test.go

Adds configuration options for maximum record size and decompressed
chunk size that will be read into byte arrays by the lexer. Defaults are
0, which is interpreted as no limit.

Go: lexer config options for max record/chunk size

---

go/cli/mcap/cmd/cat.go

Enables the cli cat command to read from stdin.

Go: enable cat cli command to read from stdin

---

python/setup.cfg

This just bumps the python library version to trigger a new PyPi distribution including recent improvements.

Bump python library version.

---

cpp/bench/CMakeLists.txt
cpp/examples/CMakeLists.txt
cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.inl
cpp/test/CMakeLists.txt

Fix clang compiler warnings, upgrade warnings to errors and enable more warnings

[C++] Enable more compiler warnings, fix warnings

---

go/cli/mcap/README.md
go/cli/mcap/cmd/convert.go

Renames --directories to --ament-prefix-path.

Rename directories parameter for ros2 conversion

---

typescript/mcap/src/v0/Mcap0StreamReader.test.ts
typescript/mcap/src/v0/Mcap0StreamReader.ts

Also fix the error message for message records missing a channel.

typescript: Improve error message for missmatched channels

---

python/README.md

The writer example produces a file studio can open.
Fixes: #272

Update python README

---

python/setup.cfg

Increment python setup.cfg version for new release.

Bump python version

---

cpp/mcap/include/mcap/internal.hpp

Fixes a few compiler warnings when compiling the C++ lib with GCC

[C++] Fix GCC compiler warnings

---

go/cli/mcap/Makefile
go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/cat_test.go
go/cli/mcap/utils/ros/json_transcoder.go
go/cli/mcap/utils/ros/json_transcoder_test.go
go/mcap/parse.go
go/ros/constants.go
go/ros/ros1msg/ros1msg_parser.go
go/ros/ros1msg/ros1msg_parser_test.go
go/ros/ros2db3_to_mcap.go
testdata/mcap/demo.mcap

Adds a ros1msg JSON transcoder to the ros utilities package, and calls
it from the CLI's cat command when the --json switch is supplied.

CLI: JSON output option for cat

---

swift/.swift-format

delete unused .swift-format file

---

typescript/examples/bag2mcap/.eslintrc.js
typescript/examples/bag2mcap/package.json
typescript/examples/bag2mcap/scripts/bag2mcap.ts
typescript/examples/bag2mcap/tsconfig.cjs.json
typescript/examples/bag2mcap/tsconfig.json
typescript/examples/bag2mcap/typings/protobufjs.d.ts
typescript/examples/bag2mcap/typings/wasm-lz4.d.ts
typescript/mcap/src/index.ts

bag2mcap converts a bag file to an mcap file with protobuf schema and message encoding.

Add typescript example bag2mcap

---

docs/.prettierrc.yml
docs/specification/mcap.ksy
package.json

None
Follow up from #308: update based on http://doc.kaitai.io/ksy_style_guide.html, fix typo, configure prettier

Update KSY definition to match style guide

---

cpp/mcap/include/mcap/types.hpp

None
Found via test failure on https://github.com/conan-io/conan-center-index/pull/9848

Add missing #include <cstddef> for std::byte

---

go/cli/mcap/cmd/schemas.go

Changes the protobuf listing to print schemas more closely formatted to
proto files. Exact compatibility is not guaranteed.

CLI: Improve schema listing support for protobuf

---

.github/workflows/ci.yml
.vscode/settings.json
python/.flake8
python/Pipfile
python/Pipfile.lock
python/mcap/mcap0/records.py
python/mcap/mcap0/stream_reader.py
python/mcap/mcap0/writer.py
python/tests/run_writer_test.py

This enables the flake8 python linter.

Setup python linter

---

.github/workflows/ci.yml
.github/workflows/pages.yml
.gitignore
cspell.config.yaml
package.json
typescript/core/package.json
yarn.lock

Documentation for the `@mcap/core` TypeScript package is now available at https://foxglove.github.io/mcap/typescript/.

Generate TS documentation using TypeDoc and publish to GitHub Pages

---

.github/workflows/pages.yml
cspell.config.yaml
python/.gitignore
python/Pipfile
python/Pipfile.lock
python/docs/conf.py
python/docs/index.rst
python/mcap/mcap0/writer.py

Python documentation is now available at https://foxglove.github.io/mcap/python/

Generate docs for Python using Sphinx

---

.github/workflows/ci.yml
.github/workflows/pages.yml
Package.resolved
Package.swift

Swift API docs are now available at https://foxglove.github.io/mcap/swift/documentation/mcap

Generate Swift documentation with DocC

---

.github/workflows/pages.yml
cpp/Makefile

None
All the build steps will run on PRs, but the publish will only run on main

Build docs on PRs, only publish on main

---

.github/workflows/pages.yml

Only publish Pages from action runs on main branch

---

.github/workflows/pages.yml

https://talk.jekyllrb.com/t/include-all-files-in-a-specific-directory-even-if-the-filenames-start-with-underscores/5849/5

pages: automatically update config to include underscored files

---

.github/workflows/pages.yml

pages: separate build into one job per language

---

cpp/hdoc.Dockerfile

None
Suggested in a comment on 91b3b2e.

pages: build optimized hdoc

---

go/cli/mcap/go.mod
go/cli/mcap/go.sum

Updates CLI dependencies for faster remote reading.

CLI: update dependencies

---

.swiftlint.yml
cspell.config.yaml
swift/conformance/Main.swift
swift/conformance/ReadConformanceRunner.swift
swift/conformance/WriteConformanceRunner.swift
swift/mcap/MCAPStreamedReader.swift
swift/mcap/MCAPWriter.swift
swift/mcap/Records.swift
tests/conformance/package.json
tests/conformance/scripts/run-tests/index.ts
tests/conformance/scripts/run-tests/runners/SwiftStreamedReaderTestRunner.ts
tests/conformance/scripts/run-tests/runners/SwiftWriterTestRunner.ts
tests/conformance/scripts/run-tests/runners/index.ts
tests/conformance/typings/json-stable-stringify.d.ts
yarn.lock

Adds `MCAPStreamedReader` class and conformance test runner for Swift.

Add Swift reader

---

docs/gh-pages/index.html
docs/gh-pages/style.css

Added basic CLI tool info to website

website: add info about CLI tool

---

cpp/.hdoc.toml
cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

cpp: bump version to 0.1.1

---

README.md

add more links and version badges to readme for each language

---

cpp/mcap/include/mcap/reader.hpp
cpp/mcap/include/mcap/reader.inl
cpp/mcap/include/mcap/writer.hpp
cpp/mcap/include/mcap/writer.inl

None
Attempting to fix build failure on Windows from https://github.com/conan-io/conan-center-index/pull/10104#issuecomment-1088038052

update includes for cstdio, use ftell/fseek instead of ftello/fseeko

---

docs/gh-pages/index.html

- Clarify which release binary to download
- Add info about the `go` command for installation

Clarify instructions for installing MCAP CLI tool

---

README.md

Graduate from beta

---

typescript/core/.yarnrc

update .yarnrc to match GitHub Actions

---

typescript/core/package.json

TypeScript v0.2.0

---

RELEASE.md

None
Tweak release instructions

Update npm release instructions

---

docs/website/index.html
docs/website/style.css

- Revise landing page with updated copy, links, etc.

Revise landing page with updated copy, links, etc.

---

go/cli/mcap/cmd/root.go

The CLI help text was very bland, I improved it.

Improve cli help text

---

python/README.md

Fix typo in Python README

---

docs/specification/mcap.ksy
tests/conformance/scripts/run-tests/runners/KaitaiStructReaderTestRunner.ts

Update mcap.ksy based on the upstream approved version from https://github.com/kaitai-io/kaitai_struct_formats/pull/592.

Update Kaitai Struct definition

---

.github/workflows/ci.yml

None
Fix PR title as requested in https://github.com/Homebrew/homebrew-core/pull/104806

Fix Homebrew PR title

---

go/cli/mcap/cmd/doctor.go

- `mcap doctor` will no longer complain about message or schema encodings that are not in the well-known list or prefixed with `x-`.
Following the latest spec

Remove checks for well-known encodings

---

typescript/core/package.json

Following the release steps here: https://github.com/foxglove/mcap/blob/main/RELEASE.md

typescript @mcap/core v0.2.2

---

cpp/examples/CMakeLists.txt
cpp/examples/conanfile.py
cpp/examples/jsonschema/CMakeLists.txt
cpp/examples/jsonschema/reader.cpp
cpp/examples/jsonschema/writer.cpp

None.
Adds JSON reading and writing examples for our C++ library.
addresses #465

C++: add JSON reader/writer example code

---

.github/workflows/ci.yml
cpp/Makefile
cpp/examples/protobuf/CMakeLists.txt
cpp/examples/protobuf/dynamic_reader.cpp
cpp/examples/protobuf/reader.cpp
cpp/examples/protobuf/static_reader.cpp
cpp/run_examples.sh

Completes the loop and adds a C++ protobuf reader example.

C++: add protobuf reader example

---

cpp/hdoc.Dockerfile
cpp/hdoc.patch

None
C++ docs now have dark mode 😮  Also less patching needed.

Upgrade hdoc to 1.3.0

---

python/mcap-ros1-support/README.md

- Fix code snippet in README for reading raw MCAP data

Fix code snippet for reading raw data

---

python/mcap-ros1-support/README.md

Missing change from ported repo

Port missing readme change from ros1-support repo

---

README.md
docs/support-matrix.md
docs/website/index.html

None
Adds documentation of our level of support and features for each library.

docs: add support matrix

---

cspell.config.yaml
docs/theme/partials/integrations/analytics/fathom.html
mkdocs.yml

See it added to every page by visiting the preview site and viewing source.

docs: add analytics script to mcap.dev

---

docs/guides/cpp/protobuf.md
mkdocs.yml

add reader example to C++ protobuf guide

---

docs/guides/cpp/protobuf.md

- Fix title
- Fix hierarchy and wording consistency for headers on the C++ / Protobuf guide

Fix title and headers on the C++ / Protobuf guide

---

docs/guides/cpp/protobuf.md
docs/guides/python/json.md
docs/guides/python/protobuf.md
docs/guides/python/ros1.md
docs/guides/python/ros2.md

- Make heading titles and hierarchy more consistent across all guides

Make heading titles and hierarchy more consistent across all guides

---

docs/guides/cpp/protobuf.md
docs/guides/python/json.md
docs/guides/python/protobuf.md
docs/guides/python/ros1.md
docs/guides/python/ros2.md

- More cleanup of sidebar titles / headers

More cleanup of sidebar titles / headers

---

docs/guides/cpp/protobuf.md

- Getting the code ready for a blog post

Copy editing for C++ / Protobuf guide

---

.github/workflows/ci.yml
.github/workflows/pages.yml
python/mcap-ros1-support/mcap_ros1/writer.py

python: correct units in ros1 writer docstrings

---

docs/specification/README.md

In preparation for addressing #577 and others, I want to clarify exactly what should be covered by the data section CRC. I have no strong preference regarding the options presented in #398, but this seems simplest considering that some of our writer implementations already do this.
Fixes #398

specification: clarify CRC coverage

---

go/cli/mcap/cmd/cat.go

cli: fix integer overflow in mcap cat args

---

.github/workflows/ci.yml
.github/workflows/pages.yml

Fixes CI for #583 
Related: https://github.com/foxglove/ws-protocol/pull/206

skip some CI steps for dependabot

---

.github/workflows/ci.yml
README.md
rust/Cargo.lock
rust/Cargo.toml

fix Rust details in top-level readme

---

mkdocs.yml

None (docs)
Partially addresses #542

Move specification to top-level

---

.github/workflows/ci.yml

None
Add info to help debug future failures

Add debug output to swiftformat CI step

---

.github/workflows/ci.yml

None
Hoping this might help fix flaky CI.

Use Docker images for swiftformat & swiftlint

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

Bump c++ library version to 0.4.0. Writer options changed in #576.
See #576

bump cpp to 0.4.0

---

docs/getting-started/json.md

Fix incorrect reference to Protobufs in JSON docs

---

.gitignore
docs/Pipfile
docs/Pipfile.lock
docs/getting-started/json.md
docs/getting-started/overview.md
docs/getting-started/protobuf.md
docs/getting-started/ros-1.md
docs/getting-started/ros-2.md
docs/guides/cpp/protobuf.md
docs/guides/python/json.md
docs/guides/python/protobuf.md
docs/guides/python/ros1.md
docs/guides/python/ros2.md
docs/home/data-serialization-formats.md
docs/home/messages-channels-and-schemas.md
docs/specification/appendix.md
docs/specification/explanatory-notes.md
mkdocs.yml

Added social preview cards to docs pages.
Cards are autogenerated by mkdocs-material and look like this:

add page descriptions and social cards

---

go/cli/mcap/cmd/add.go
go/cli/mcap/cmd/attachment.go
go/cli/mcap/cmd/attachments.go
go/cli/mcap/cmd/cat.go
go/cli/mcap/cmd/channels.go
go/cli/mcap/cmd/chunks.go
go/cli/mcap/cmd/convert.go
go/cli/mcap/cmd/doctor.go
go/cli/mcap/cmd/get.go
go/cli/mcap/cmd/info.go
go/cli/mcap/cmd/list.go
go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/metadata.go
go/cli/mcap/cmd/root.go
go/cli/mcap/cmd/schemas.go
go/mcap/indexed_message_iterator.go
go/mcap/lexer.go
python/mcap/mcap/mcap0/reader.py
rust/examples/conformance_reader.rs
rust/examples/recover.rs
typescript/examples/validate/scripts/validate.ts

None
Made capitalization and casing more consistent in CLI tool and some other libraries' help/error messages

more consistent capitalization/casing

---

docs/guides/python/ros2.md

Just pulling from the existing ros2 examples in `python/examples/ros2`.

docs: add ros2 python writer example

---

docs/getting-started/ros-2.md

Add a note to point users to `ros2 bag convert` if mcap convert doesn't work for them.

docs: add note about ros2 bag convert

---

.github/workflows/ci.yml
python/Makefile

python: publish mcap-ros2-support to pypi, testpypi

---

.github/workflows/ci.yml
go/mcap/version.go

run CI on go/mcap tags

---

rust/Cargo.toml

None
Fix rust tests by adding back serde as a dev dependency.

Fix rust tests by adding serde as a dev dependency

---

docs/getting-started/ros-2.md

docs: add ros2 bag record instructions

---

.lfsconfig

None
Attempted workaround for https://forums.swift.org/t/swiftpm-with-git-lfs/42396/4 / https://github.com/apple/swift-package-manager/issues/5351.

Add .lfsconfig to work around SwiftPM bug

---

docs/specification/appendix.md

Fix bad link in documentation.

Fix Wikipedia link for LZ4

---

go/cli/mcap/cmd/doctor.go

doctor: fix format string for empty schema

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

Bumps the C++ library version to v0.7.0.

cpp: update version to v0.7.0

---

rust/Cargo.toml

**User-facing changes**
- #653 
- #754 
Fixes #756

rust: release 0.6.0

---

cpp/mcap/conanfile.py

cpp: update to lz4 1.9.4

---

.github/workflows/ci.yml

Filed https://github.com/pypa/gh-action-pypi-publish/issues/115 for an issue with 1.6.2 - seems like an ongoing issue. Pin 1.5 for now until that's resolved.

ci.yml: pin pypa release action v1.5

---

go/mcap/version.go

Create a new release of the `go` MCAP library.
Changelog:
* Add a `Close()` method on Lexer to allow for proper cleanup of LZ4 decompressor contexts
* Fix bug where the indexed reader would loop infinitely attempting to read the summary section of an indexed file if no Statistics record exists in the summary.
* When reading in log time order, Messages returned by the indexed reader are ordered by file order when timestamps are equivalent.
* Fix bug where messages with timestamp 0 would not be counted when calculating the MessageStartTime in the summary.

go: update version to v0.4.0

---

docs/index.md

Revised History section for flow ("As a container format, MCAP solves many of these issues" should be the first sentence in the "After MCAP" section)

Revise History section for flow

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

cpp: bump to v1.0.0

---

typescript/core/package.json

typescript: mcap/core: bump to v1.0.0

---

typescript/core/package.json

TypeScript @mcap/core 1.1.0

---

go/cli/mcap/cmd/filter.go

- [cli] `mcap decompress` command, alias for `mcap compress --compression "none"`

[cli] Add `mcap decompress` command

---

docs/guides/python/ros2.md

ROS2 example now handles non-String messages. Leads to a smoother intro for ROS 2 users with existing bags.
Fixes #745

docs: ros2: handle case using rosbag2_py for non-string msgs

---

docs/specification/README.md

specification: clarify where channels can be recorded

---

python/mcap/mcap/writer.py

python: fix doc generation for Writer

---

.vscode/launch.json
typescript/core/package.json

- [TypeScript] `@mcap/core` 1.2.0 release

@mcap/core 1.2.0

---

go/cli/mcap/cmd/merge.go
go/cli/mcap/cmd/merge_test.go

Fixed a bug where `mcap merge` would incorrectly change some channels' schemas.
Fixed a bug where `mcap merge` would crash on some input files with schemaless channels (schemaId=0).
Fixes #837

fix bad mutation in merge

---

cspell.config.yaml
docs/specification/README.md

specification: remove errant extra line

---

website/docusaurus.config.js

Use sentence case in footer

---

go/mcap/README.md
website/docs/reference/index.md

Use 'API reference' for consistency with previously made changes

---

website/docs/spec/index.md

In the description of the summary section, swaps the location of "metadata index" and "statistics". Files can be written in either order technically, but this is what our libraries do. Metadata indexes are also more logically grouped with attachment indexes.
In the listing of records, arranges the "data portion" records above the summary section records.

Docs: rearrange record ordering more logically

---

website/src/components/McapRecordingDemo/McapRecordingDemo.tsx

Make demo copy more concise

---

website/docs/reference/index.md

These footnotes got swapped at some point

fix footnotes in feature matrix

---

website/src/components/McapRecordingDemo/McapRecordingDemo.tsx
website/src/components/McapRecordingDemo/videoCapture.ts

Camera feed now appears immediately when "Camera" is toggled on, even if recording has not started yet.

demo: show camera immediately when enabled

---

website/docusaurus.config.js

None
Fathom requires additional configuration to track SPA page loads

Website: Configure Fathom for SPA

---

typescript/core/src/McapIndexedReader.ts

None
Respect the `validateCrc` option in `readMessages` in McapIndexedReader when reading chunks instead of always validating. Since validating the crc on the chunk data is likely to be the most expensive crc check we should respect the client's wishes and skip it when crc validation is turned off in the parent `readMessges` call.

Respect validateCrc option for chunk reading in typescript indexed reader

---

.github/workflows/website.yml

None
Update Cloudflare secret to match GitHub

Website: Fix deployment key

---

website/docs/spec/index.md

Spec: improve description of sequence field

---

website/docs/guides/cli.md

- Revise docs for CLI to include correct release download link

Revise docs for CLI to include correct release download link

---

.github/workflows/ci.yml

None
Fixes these publish failures: https://github.com/foxglove/mcap/actions/runs/6938564046/job/18874494476

fix npm publish incantation

---

.github/workflows/ci.yml

None
More of the same #1026. Some day the packages will be published.

Fix publish incantation again

---

typescript/core/src/parse.ts

None
Very marginal performance improvements

@mcap/core: Avoid unnecessary bigint conversion

---

typescript/core/src/McapIndexedReader.ts

@mcap/core: Avoid heap operations when chunks are ordered
When chunks are ordered and not overlapping, we do not need to re-evaluate the heap after every message and can instead keep on reading from the current chunk.

@mcap/core: Avoid heap operations when chunks are ordered

---

typescript/core/package.json

typescript: bump @mcap/core to v2.0.2

---

README.md

- N/A
- Update README.md with release link for CLI tool

Update README.md with release link for CLI tool

---

README.md

- None
- Fix release link for CLI tool in README

Fix release link for CLI tool in README

---

website/docusaurus.config.js

add a foxglove link to the mcap website header
update foxglove links in the mcap website footer
post foxglove 2.0 foxglove.dev URLs have changed
n/a

update foxglove header/footer menu links on mcap website

---

README.md

Adds a suggested bibtex citation to the README.

Add sample bibtex citation to README

---

rust/Cargo.toml

Bump rust to 0.9.1

---

typescript/core/package.json

Performance improvements (#1212)

Bump @mcap/core version

---

go/mcap/version.go

bump go version to v1.6.0

---

rust/Cargo.toml

None
None
Bump the Rust code to 0.12.0 to release the linear writer feature.
</td><td>

rust: release version 0.12.0

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

- Writer: updated the behavior of the chunk_size option to be a soft upper bound on chunk size instead of a lower bound.
See docstrings in `writer.hpp`.

cpp: bump to v2.0.0

---

typescript/support/package.json

@mcap/support: release 1.0.3

---

rust/Cargo.toml

- Added: Added options to disable CRC calculations in the rust writer
- Changed: reduce allocations while writing messages
</td><td>

rust: bump cargo version

---

.github/workflows/ci.yml
.github/workflows/website.yml
.swiftlint.yml
Package.resolved
Package.swift
swift/conformance/ReadConformanceRunner.swift
swift/crc/CRC32.swift
swift/mcap/MCAPRandomAccessReader.swift
swift/mcap/MCAPStreamedReader.swift
swift/mcap/Records.swift
swift/test/MCAPRandomAccessReaderTests.swift

Swift: updated dependencies to latest versions of swift-collections etc.
None
Resolves https://github.com/foxglove/mcap/discussions/1332
Most code changes are auto fixes from linters/formatters, and there was a small `.min()` -> `.min` change in the Heap API

Upgrade Swift dependencies

---

README.md

None
None
Update releases link for MCAP CLI to filter only CLI releases.

Readme: Update CLI link

---

typescript/core/src/ChunkCursor.ts

None
None
`... with logTime with logTime ...` -> `... with logTime ...`

typescript: fix duplicated words in error message

---

cpp/bench/conanfile.py
cpp/build-docs.sh
cpp/build.sh
cpp/docs/conanfile.py
cpp/examples/conanfile.py
cpp/mcap/conanfile.py
cpp/mcap/include/mcap/types.hpp
cpp/test/conanfile.py

- Fix a few bugs related to message-less chunks
- Add a missing cstdint include that causes a build error with GCC 15.1.1
None
Just bumping the version, using #1305 as an example.

cpp: Bump to v2.0.1

---

rust/Cargo.toml

rust: bump version number

---

typescript/browser/package.json
typescript/support/package.json

- #1423 
None
Releasing to get the latest readmes on npm

TS: version bumps for @mcap/browser and @mcap/support

---

python/examples/jsonschema/pointcloud_csv_to_mcap.py

Add missing z option to example command
Error without the flag: 
```
Archive is compressed. Use -z option
```

Update example command for pointcloud_csv_to_mcap.py

---

website/docs/guides/getting-started/ros-2.md

https://shouldiputaspacebetweenrosand2.com

Fix typos in ROS 2 getting started guide

---

rust/src/read.rs

Avoid a few copies by using `HashMap::entry` in the `ChannelAccumulator`.

rust: Use HashMap::entry in ChannelAccumulator

---

website/docs/spec/registry.md

None
None
The `-P` flag suppresses line marker generation in GCC and Clang, no `grep` needed.
Also added `-x c` to prevent them from treating `.idl` files as linker scripts, since they still tokenize before preprocessing. And tried to make the instructions a little bit clearer.

docs: remove `grep` from `omgidl` prep instructions
